/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventario;

import java.awt.Color;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;
import setConection.Conexion;

/**
 *
 * @author easyb
 */
public class Archivos extends javax.swing.JFrame {
    int contador = 0;
    int dia=0,mes=0,anio=0;
    String fecha;

    /**
     * Creates new form Archivos
     */
    public Archivos() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        primerValor.getEditor().getComponent(0).setBackground(new Color(70,75,100));
        primerValor.getEditor().getComponent(0).setForeground(new Color(187,197,207));
        segundoValor.getEditor().getComponent(0).setBackground(new Color(70,75,100));
        segundoValor.getEditor().getComponent(0).setForeground(new Color(187,197,207));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ArchivoDiario = new javax.swing.JButton();
        ArchivoMensual = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        productosPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Nombre_Field = new javax.swing.JTextField();
        CrearProductos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Marca_Field = new javax.swing.JTextField();
        CrearMarca = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        primerValor = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        segundoValor = new javax.swing.JSpinner();
        CrearPrecio = new javax.swing.JButton();
        RegresarButton = new javax.swing.JButton();
        AyudaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Generador de Archivos");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(110, 140, 100));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 0));
        jLabel2.setText("CREACION DE ARCHIVOS");

        ArchivoDiario.setBackground(new java.awt.Color(70, 75, 90));
        ArchivoDiario.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        ArchivoDiario.setForeground(new java.awt.Color(51, 255, 51));
        ArchivoDiario.setText("Archivo/Diario");
        ArchivoDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchivoDiarioActionPerformed(evt);
            }
        });

        ArchivoMensual.setBackground(new java.awt.Color(70, 75, 90));
        ArchivoMensual.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        ArchivoMensual.setForeground(new java.awt.Color(51, 255, 51));
        ArchivoMensual.setText("Archivo/Mensual");
        ArchivoMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchivoMensualActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 0));
        jLabel5.setText("ARCHIVOS DE VENTAS");

        productosPanel.setBackground(new java.awt.Color(100, 110, 130));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 0));
        jLabel3.setText("Archivo/Nombres:");

        Nombre_Field.setBackground(new java.awt.Color(70, 75, 100));
        Nombre_Field.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Nombre_Field.setForeground(new java.awt.Color(187, 197, 207));
        Nombre_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_FieldActionPerformed(evt);
            }
        });

        CrearProductos.setBackground(new java.awt.Color(70, 75, 110));
        CrearProductos.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        CrearProductos.setForeground(new java.awt.Color(51, 255, 51));
        CrearProductos.setText("Crear");
        CrearProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearProductosActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 0));
        jLabel4.setText("Archivo/Marca:");

        Marca_Field.setBackground(new java.awt.Color(70, 75, 100));
        Marca_Field.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Marca_Field.setForeground(new java.awt.Color(187, 197, 207));

        CrearMarca.setBackground(new java.awt.Color(70, 75, 110));
        CrearMarca.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        CrearMarca.setForeground(new java.awt.Color(51, 255, 51));
        CrearMarca.setText("Crear");
        CrearMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearMarcaActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 0));
        jLabel1.setText("Archivo/Precio:");

        jLabel7.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 0));
        jLabel7.setText("Desde");

        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 0));
        jLabel6.setText("hasta");

        CrearPrecio.setBackground(new java.awt.Color(70, 75, 110));
        CrearPrecio.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        CrearPrecio.setForeground(new java.awt.Color(51, 255, 51));
        CrearPrecio.setText("Crear");
        CrearPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearPrecioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout productosPanelLayout = new javax.swing.GroupLayout(productosPanel);
        productosPanel.setLayout(productosPanelLayout);
        productosPanelLayout.setHorizontalGroup(
            productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productosPanelLayout.createSequentialGroup()
                        .addGroup(productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Nombre_Field, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                            .addComponent(Marca_Field))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CrearMarca, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CrearProductos, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(productosPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(primerValor, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(segundoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(CrearPrecio)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        productosPanelLayout.setVerticalGroup(
            productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productosPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CrearProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Nombre_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Marca_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CrearMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(primerValor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(segundoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CrearPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        RegresarButton.setBackground(new java.awt.Color(90, 0, 0));
        RegresarButton.setFont(new java.awt.Font("Segoe UI Symbol", 0, 28)); // NOI18N
        RegresarButton.setForeground(new java.awt.Color(200, 0, 0));
        RegresarButton.setText("↩");
        RegresarButton.setToolTipText("Regresar");
        RegresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarButtonActionPerformed(evt);
            }
        });

        AyudaButton.setBackground(new java.awt.Color(102, 102, 0));
        AyudaButton.setFont(new java.awt.Font("Segoe UI Symbol", 0, 30)); // NOI18N
        AyudaButton.setForeground(new java.awt.Color(255, 255, 0));
        AyudaButton.setText("?");
        AyudaButton.setToolTipText("Ayuda");
        AyudaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyudaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(productosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(ArchivoDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(ArchivoMensual, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(RegresarButton)
                .addGap(105, 105, 105)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AyudaButton)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(RegresarButton)
                    .addComponent(AyudaButton))
                .addGap(18, 18, 18)
                .addComponent(productosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ArchivoDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArchivoMensual, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearMarcaActionPerformed
        // TODO add your handling code here:
        contador++;
        //Creacion del archivo
        System.out.println(Marca_Field.getText());
        if(Marca_Field.getText().trim().matches("[\\w\\s]{1,50}")){
            System.out.println(Marca_Field.getText());
            Conexion objConexion = new Conexion();
            String strSentenciaInsert = String.format("SELECT * FROM Inventario WHERE Marca='"+Marca_Field.getText()+"'");
            objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
            try{
                FileSystemView view = FileSystemView.getFileSystemView();
                File file = view.getHomeDirectory();
                String desktopPath = file.getPath();
                File archivo = new File(desktopPath + "/Archivo Marca "+ contador + ".txt");
                FileWriter editor = new FileWriter(desktopPath + "/Archivo Marca "+ contador + ".txt");
                ResultSet resultado=objConexion.consultarRegistro("SELECT * FROM Inventario WHERE Marca='"+Marca_Field.getText()+"'");
                while(resultado.next()){
                    editor.write(resultado.getString("Codigo_Barras")+" " + resultado.getString("Nombre")+ 
                        " " + resultado.getString("Precio")+ " " + resultado.getString("Marca")+ " " + resultado.getString("Fecha_Ingreso")+ " " +
                        " " + resultado.getString("Stock")+ " " + resultado.getString("Tipo")+ " " + resultado.getString("Ventas_Dia")+ " " + resultado.getString("Ventas_Mes") + "\n");
                }
                editor.close();
                JOptionPane.showMessageDialog(null, "Se ha generado el Archivo correctamente","Archivo Marca",JOptionPane.INFORMATION_MESSAGE);
                System.out.println("Archivo Creado con Exito en el Escritorio");
                System.out.println(archivo.getName());
            }catch(Exception e){
                System.out.println("Error de consulta "+e);
                System.out.println("Error al crear el archivo"+e);
                JOptionPane.showMessageDialog(null, "No se ha generado el Archivo correctamente","Archivo Marca",JOptionPane.ERROR_MESSAGE);
            }
            objConexion.close();
        }else{
            JOptionPane.showMessageDialog(null,"El campo 'Marca' tiene un valor no válido, No se creo el archivo","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CrearMarcaActionPerformed

    private void CrearPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearPrecioActionPerformed
        // TODO add your handling code here:
         contador++;
        //Creacion del archivo
        //Esperar a Alberto xd
        Conexion objConexion = new Conexion();
        String strSentenciaInsert = String.format("SELECT * FROM Inventario WHERE Precio BETWEEN %s AND %s ORDER BY Precio",primerValor.getValue(),segundoValor.getValue());
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        try{
            FileSystemView view = FileSystemView.getFileSystemView();
            File file = view.getHomeDirectory();
            String desktopPath = file.getPath();
            File archivo = new File(desktopPath + "/Archivo Precio "+ contador + ".txt");
            FileWriter editor = new FileWriter(desktopPath + "/Archivo Precio "+ contador + ".txt");
            ResultSet resultado=objConexion.consultarRegistro("SELECT * FROM Inventario WHERE Precio BETWEEN "+primerValor.getValue() +" AND "+segundoValor.getValue() +" ORDER BY Precio");
            while(resultado.next()){
                editor.write(resultado.getString("Codigo_Barras")+" " + resultado.getString("Nombre")+ 
                    " " + resultado.getString("Precio")+ " " + resultado.getString("Marca")+ " " + resultado.getString("Fecha_Ingreso")+ " " +
                    " " + resultado.getString("Stock")+ " " + resultado.getString("Tipo")+ " " + resultado.getString("Ventas_Dia")+ " " + resultado.getString("Ventas_Mes") + "\n");

            }
            editor.close();
            JOptionPane.showMessageDialog(null, "Se ha generado el Archivo correctamente","Archivo Precio",JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Archivo Creado con Exito en el Escritorio");
            System.out.println(archivo.getName());
        }catch(Exception e){
            System.out.println("Error de consulta "+e);
            System.out.println("Error al crear el archivo"+e);
            JOptionPane.showMessageDialog(null, "No se ha generado el Archivo correctamente","Archivo Precio",JOptionPane.ERROR_MESSAGE);
        }
        objConexion.close();
    }//GEN-LAST:event_CrearPrecioActionPerformed

    private void CrearProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearProductosActionPerformed
        // TODO add your handling code here:
        contador++;
        //Creacion del archivo
        //Esperar a Alberto xd
        System.out.println(Nombre_Field.getText());
        if(Nombre_Field.getText().trim().matches("[\\w\\s]{1,100}")){
            System.out.println(Nombre_Field.getText());
            Conexion objConexion = new Conexion();
            String strSentenciaInsert = String.format("SELECT * FROM Inventario WHERE Nombre='"+Nombre_Field.getText()+"'");
            objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
            try{
                FileSystemView view = FileSystemView.getFileSystemView();
                File file = view.getHomeDirectory();
                String desktopPath = file.getPath();
                File archivo = new File(desktopPath + "/Archivo Nombre "+ contador + ".txt");
                FileWriter editor = new FileWriter(desktopPath + "/Archivo Nombre "+ contador + ".txt");
                ResultSet resultado=objConexion.consultarRegistro("SELECT * FROM Inventario WHERE Nombre='"+Nombre_Field.getText()+"'");
                while(resultado.next()){
                    editor.write(resultado.getString("Codigo_Barras")+" " + resultado.getString("Nombre")+ 
                        " " + resultado.getString("Precio")+ " " + resultado.getString("Marca")+ " " + resultado.getString("Fecha_Ingreso")+ " " +
                        " " + resultado.getString("Stock")+ " " + resultado.getString("Tipo")+ " " + resultado.getString("Ventas_Dia")+ " " + resultado.getString("Ventas_Mes") + "\n");
                    
                }
                editor.close();
                JOptionPane.showMessageDialog(null, "Se ha generado el Archivo correctamente","Archivo Nombre",JOptionPane.INFORMATION_MESSAGE);
                System.out.println("Archivo Creado con Exito en el Escritorio");
                System.out.println(archivo.getName());
            }catch(Exception e){
                System.out.println("Error de consulta "+e);
                System.out.println("Error al crear el archivo"+e);
                JOptionPane.showMessageDialog(null, "No se ha generado el Archivo correctamente","Archivo Nombre",JOptionPane.ERROR_MESSAGE);
            }
            objConexion.close();
        }else{
            
            JOptionPane.showMessageDialog(null,"El campo 'Nombre' tiene un valor no válido, No se creo el archivo","Error",JOptionPane.ERROR_MESSAGE);
        }    
    }//GEN-LAST:event_CrearProductosActionPerformed

    private void Nombre_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_FieldActionPerformed

    private void ArchivoDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchivoDiarioActionPerformed
        // TODO add your handling code here:
        //Creacion del archivo
        //Creacion del archivo
        //Esperar a Alberto xd
        Conexion objConexion = new Conexion();
        String strSentenciaInsert = String.format("SELECT * FROM Inventario WHERE Ventas_Dia>0");
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        try{
            FileSystemView view = FileSystemView.getFileSystemView();
            File file = view.getHomeDirectory();
            String desktopPath = file.getPath();
            calcula();
            File archivo = new File(desktopPath + "/Archivo Diario "+ fecha + ".txt");
            FileWriter editor = new FileWriter(desktopPath + "/Archivo Diario "+ fecha + ".txt");
            ResultSet resultado=objConexion.consultarRegistro("SELECT * FROM Inventario WHERE Ventas_Dia>0");
            while(resultado.next()){
                editor.write(resultado.getString("Codigo_Barras")+" " + resultado.getString("Nombre")+ 
                    " " + resultado.getString("Precio")+ " " + resultado.getString("Marca")+ " " + resultado.getString("Fecha_Ingreso")+ " " +
                    " " + resultado.getString("Stock")+ " " + resultado.getString("Tipo")+ " " + resultado.getString("Ventas_Dia")+ " " + resultado.getString("Ventas_Mes") + "\n");

            }
            editor.close();
            JOptionPane.showMessageDialog(null, "Se ha generado el Archivo correctamente","Archivo Diario",JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Archivo Creado con Exito en el Escritorio");
            System.out.println(archivo.getName());
        }catch(Exception e){
            System.out.println("Error al crear el archivo, no hay ventas diarias existentes"+e);
            JOptionPane.showMessageDialog(null, "No se ha generado el Archivo correctamente","Archivo Diario",JOptionPane.ERROR_MESSAGE);
        }
        objConexion.close();
    }//GEN-LAST:event_ArchivoDiarioActionPerformed

    private void ArchivoMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchivoMensualActionPerformed
        // TODO add your handling code here:
        //Creacion del archivo
        Conexion objConexion = new Conexion();
        String strSentenciaInsert = String.format("SELECT * FROM Inventario WHERE Ventas_Mes>0");
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        try{
            FileSystemView view = FileSystemView.getFileSystemView();
            File file = view.getHomeDirectory();
            String desktopPath = file.getPath();
            calcula();
            File archivo = new File(desktopPath + "/Archivo Mensual "+ fecha + ".txt");
            FileWriter editor = new FileWriter(desktopPath + "/Archivo Mensual "+ fecha + ".txt");
            ResultSet resultado=objConexion.consultarRegistro("SELECT * FROM Inventario WHERE Ventas_Mes>0");
            while(resultado.next()){
                editor.write(resultado.getString("Codigo_Barras")+" " + resultado.getString("Nombre")+ 
                    " " + resultado.getString("Precio")+ " " + resultado.getString("Marca")+ " " + resultado.getString("Fecha_Ingreso")+ " " +
                    " " + resultado.getString("Stock")+ " " + resultado.getString("Tipo")+ " " + resultado.getString("Ventas_Dia")+ " " + resultado.getString("Ventas_Mes") + "\n");

            }
            editor.close();
            JOptionPane.showMessageDialog(null, "Se ha generado el Archivo correctamente","Archivo Mensual",JOptionPane.INFORMATION_MESSAGE);
            System.out.println("Archivo Creado con Exito en el Escritorio");
            System.out.println(archivo.getName());
        }catch(Exception e){
            System.out.println("Error al crear el archivo, no hay ventas Mensuales existentes"+e);
            JOptionPane.showMessageDialog(null, "No se ha generado el Archivo correctamente","Archivo Mensual",JOptionPane.ERROR_MESSAGE);
        }
        objConexion.close();
    }//GEN-LAST:event_ArchivoMensualActionPerformed

    private void RegresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_RegresarButtonActionPerformed

    private void AyudaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyudaButtonActionPerformed
        // TODO add your handling code here:
        //textblock
        JOptionPane.showMessageDialog(null, """
            Se creará un archivo en el escritorio en base a un campo, se debe
            de escribir el dato seleccionado y después pulsar su botón "Crear".
            Tambíen se puede crear en base a las ventas diarias y ventas mensuales""", "Ayuda", JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_AyudaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Archivos().setVisible(true);
            }
        });
    }
    
    private void calcula(){
        Calendar calendario = new GregorianCalendar();
        Date fechaActual = new Date();
        calendario.setTime(fechaActual);
        dia = calendario.get(Calendar.DAY_OF_MONTH);
        mes = calendario.get(Calendar.MONTH) + 1;       //el mes marca un numero menor
        anio = calendario.get(Calendar.YEAR);
        if(dia < 10){
            if(mes < 10)
                fecha = String.format("%d-0%d-0%d", anio,mes,dia);  //si el dia y el mes son menores que 10
            fecha = String.format("%d-%d-0%d", anio,mes,dia);       //si SOLO el dia es menor que 10
        }
        if(mes < 10)
            fecha = String.format("%d-0%d-%d", anio,mes,dia);       //si SOLO el mes es menor que 10
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ArchivoDiario;
    private javax.swing.JButton ArchivoMensual;
    private javax.swing.JButton AyudaButton;
    private javax.swing.JButton CrearMarca;
    private javax.swing.JButton CrearPrecio;
    private javax.swing.JButton CrearProductos;
    private javax.swing.JTextField Marca_Field;
    private javax.swing.JTextField Nombre_Field;
    private javax.swing.JButton RegresarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner primerValor;
    private javax.swing.JPanel productosPanel;
    private javax.swing.JSpinner segundoValor;
    // End of variables declaration//GEN-END:variables
}
