/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventario;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import setConection.Conexion;
import set_get_data.Data_information;

/**
 *
 * @author easyb
 */
public class Baja extends javax.swing.JFrame {

    /**
     * Creates new form Baja
     */
    DefaultTableModel modelo;
    Data_information objInventario = null;
    
    public Baja() {
        initComponents();
        this.setLocationRelativeTo(null);
        String[] titulos={"Codigo de Barras","Nombre","Precio","Marca","Fecha de Ingreso","Stock","Tipo","Ventas del dia","Ventas del mes","Descuentos"};
        modelo = new DefaultTableModel(null, titulos);
        tablaVentas.setModel(modelo);
        mostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        AceptarButton = new javax.swing.JButton();
        ActualizarButton = new javax.swing.JButton();
        RegresarButton = new javax.swing.JButton();
        AyudaButton = new javax.swing.JButton();

        setTitle("Ventas");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(110, 140, 100));

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo de Barras", "Nombre", "Precio", "Marca", "Fecha ", "Stock", "Tipo", "Ventas Diarias", "Ventas Mensuales", "Descuento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaVentas.getTableHeader().setReorderingAllowed(false);
        tablaVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaVentas);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 0));
        jLabel2.setText("BAJAS/VENTAS");

        AceptarButton.setBackground(new java.awt.Color(0, 205, 20));
        AceptarButton.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        AceptarButton.setForeground(new java.awt.Color(0, 55, 0));
        AceptarButton.setText("ACEPTAR");
        AceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarButtonActionPerformed(evt);
            }
        });

        ActualizarButton.setBackground(new java.awt.Color(50, 50, 0));
        ActualizarButton.setFont(new java.awt.Font("Segoe UI Symbol", 0, 30)); // NOI18N
        ActualizarButton.setForeground(new java.awt.Color(150, 200, 0));
        ActualizarButton.setText("↻");
        ActualizarButton.setToolTipText("Actualizar");
        ActualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarButtonActionPerformed(evt);
            }
        });

        RegresarButton.setBackground(new java.awt.Color(90, 0, 0));
        RegresarButton.setFont(new java.awt.Font("Segoe UI Symbol", 0, 28)); // NOI18N
        RegresarButton.setForeground(new java.awt.Color(200, 0, 0));
        RegresarButton.setText("↩");
        RegresarButton.setToolTipText("Regresar");
        RegresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarButtonActionPerformed(evt);
            }
        });

        AyudaButton.setBackground(new java.awt.Color(102, 102, 0));
        AyudaButton.setFont(new java.awt.Font("Segoe UI Symbol", 0, 30)); // NOI18N
        AyudaButton.setForeground(new java.awt.Color(255, 255, 0));
        AyudaButton.setText("?");
        AyudaButton.setToolTipText("Ayuda");
        AyudaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyudaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(RegresarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(236, 236, 236)
                .addComponent(AyudaButton)
                .addGap(18, 18, 18)
                .addComponent(ActualizarButton)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(382, Short.MAX_VALUE)
                .addComponent(AceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(380, 380, 380))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ActualizarButton)
                    .addComponent(RegresarButton)
                    .addComponent(AyudaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarButtonActionPerformed
        // TODO add your handling code here:
        Conexion objConexion = new Conexion();
        if(objInventario != null){
            String cantS = JOptionPane.showInputDialog(null,"¿Cantidad a dar de baja?","Baja",JOptionPane.INFORMATION_MESSAGE);
            if(cantS != null){
                if(cantS.equals(""))
                    JOptionPane.showMessageDialog(null, "Inserte un valor no nulo","Error",JOptionPane.ERROR_MESSAGE);
                else{
                    if(cantS.matches("\\d+")){
                        int cant = Integer.parseInt(cantS);
                        if(cant > objInventario.getStock())
                            JOptionPane.showMessageDialog(null, "La cantidad no debe superar al stock","Error",JOptionPane.ERROR_MESSAGE);
                        else{
                            String strSentenciaInsert = String.format("UPDATE Inventario SET Stock=%d,Ventas_Dia=%d WHERE Codigo_barras=%d", 
                                objInventario.getStock()-cant, objInventario.getVentasDia()+cant, objInventario.getCodigo_barras());
                            if(objConexion.ejecutarSentenciaSQL(strSentenciaInsert) == 1)
                                JOptionPane.showMessageDialog(null, "Venta realizada con éxito", "Ventas", JOptionPane.INFORMATION_MESSAGE);
                            else
                                JOptionPane.showMessageDialog(null, "Error al realizar la venta", "Ventas", JOptionPane.ERROR_MESSAGE);                        }
                    }else
                        JOptionPane.showMessageDialog(null, "Inserte un valor numérico","Error",JOptionPane.ERROR_MESSAGE);
                }
            }
            objInventario = null;
        }
        objConexion.close();
        mostrarDatos();
    }//GEN-LAST:event_AceptarButtonActionPerformed

    private void ActualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarButtonActionPerformed
        // TODO add your handling code here:
        mostrarDatos();
    }//GEN-LAST:event_ActualizarButtonActionPerformed

    private void tablaVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVentasMouseClicked
        // TODO add your handling code here:
        objInventario = new Data_information();
        if(evt.getClickCount()==1){
            JTable receptor = (JTable)evt.getSource();
            String auxCodBarras = receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString();
            objInventario.setCodigo_barras(Long.parseLong(auxCodBarras));
            String auxStock = receptor.getModel().getValueAt(receptor.getSelectedRow(), 5).toString();
            objInventario.setStock(Integer.parseInt(auxStock));
            String auxVentasDia = receptor.getModel().getValueAt(receptor.getSelectedRow(), 7).toString();
            objInventario.setVentasDia(Integer.parseInt(auxVentasDia));
        }
    }//GEN-LAST:event_tablaVentasMouseClicked

    private void RegresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_RegresarButtonActionPerformed

    private void AyudaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyudaButtonActionPerformed
        // TODO add your handling code here:
        //textblock
        JOptionPane.showMessageDialog(null, """
            Para dar de baja/vender un producto se debe seleccionar la fila o el dato a dar de baja/vender,
            después se debe pulsar el botón aceptar""", "Ayuda", JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_AyudaButtonActionPerformed

    public void mostrarDatos(){
        //limpiar la tabla cada que se hace una llamada a mostrar datos
        while(modelo.getRowCount()>0)
            modelo.removeRow(0);
        Conexion objConexion=new Conexion();
        try{
            ResultSet resultado=objConexion.consultarRegistro("SELECT * FROM Inventario");
            while(resultado.next()){
                Object[] objUsuario = {resultado.getString("Codigo_Barras"), resultado.getString("Nombre"), 
                    resultado.getString("Precio"), resultado.getString("Marca"), resultado.getString("Fecha_Ingreso"), 
                    resultado.getString("Stock"), resultado.getString("Tipo"), resultado.getString("Ventas_Dia"), 
                    resultado.getString("Ventas_Mes"), resultado.getString("Descuento")};
                modelo.addRow(objUsuario);
            }
        }catch(Exception e){
            System.out.println("Error de consulta "+e);
        }
        objConexion.close();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Baja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Baja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Baja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Baja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Baja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarButton;
    private javax.swing.JButton ActualizarButton;
    private javax.swing.JButton AyudaButton;
    private javax.swing.JButton RegresarButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaVentas;
    // End of variables declaration//GEN-END:variables
}
