/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventario;

import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import setConection.Conexion;
import set_get_data.Data_information;
import set_get_data.getData;
/**
 *
 * @author easyb
 */
public class RegistroF extends javax.swing.JFrame implements getData, Runnable{
    boolean error=false;
    int dia=0,mes=0,anio=0;
    String fecha;
    Thread hilo;
    
    /**
     * Creates new form RegistroF
     */
    public RegistroF() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AceptarButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Codigo_Field = new javax.swing.JTextField();
        Precio_Field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Nombre_Field = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Cant_Field = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Marca_Field = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        tipoBox = new javax.swing.JComboBox<>();
        RegresarButton = new javax.swing.JButton();
        AyudaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(110, 140, 100));

        AceptarButton.setBackground(new java.awt.Color(0, 205, 20));
        AceptarButton.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        AceptarButton.setForeground(new java.awt.Color(0, 55, 0));
        AceptarButton.setText("ACEPTAR");
        AceptarButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 51));
        jLabel2.setText("Registro de Producto");

        jPanel2.setBackground(new java.awt.Color(100, 110, 130));

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(31, 210, 21));
        jLabel1.setText("Codigo de Barras:");

        Codigo_Field.setBackground(new java.awt.Color(70, 75, 100));
        Codigo_Field.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Codigo_Field.setForeground(new java.awt.Color(187, 197, 187));
        Codigo_Field.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(20, 50, 100))); // NOI18N
        Codigo_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Codigo_FieldActionPerformed(evt);
            }
        });

        Precio_Field.setBackground(new java.awt.Color(70, 75, 100));
        Precio_Field.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Precio_Field.setForeground(new java.awt.Color(187, 197, 187));
        Precio_Field.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(20, 50, 100))); // NOI18N
        Precio_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Precio_FieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(31, 210, 21));
        jLabel3.setText("Nombre:");

        Nombre_Field.setBackground(new java.awt.Color(70, 75, 100));
        Nombre_Field.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Nombre_Field.setForeground(new java.awt.Color(187, 197, 187));
        Nombre_Field.setToolTipText("");
        Nombre_Field.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(20, 50, 100))); // NOI18N
        Nombre_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nombre_FieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(31, 210, 21));
        jLabel4.setText("Precio:");

        Cant_Field.setBackground(new java.awt.Color(70, 75, 100));
        Cant_Field.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Cant_Field.setForeground(new java.awt.Color(187, 197, 187));
        Cant_Field.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(20, 50, 100))); // NOI18N
        Cant_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cant_FieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(31, 210, 21));
        jLabel5.setText("Marca:");

        Marca_Field.setBackground(new java.awt.Color(70, 75, 100));
        Marca_Field.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Marca_Field.setForeground(new java.awt.Color(187, 197, 187));
        Marca_Field.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(20, 50, 100))); // NOI18N
        Marca_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Marca_FieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(31, 210, 21));
        jLabel6.setText("Cantidad:");

        jLabel7.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(31, 210, 21));
        jLabel7.setText("Descuento:");

        jLabel8.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(31, 210, 21));
        jLabel8.setText("Tipo:");

        jComboBox1.setBackground(new java.awt.Color(70, 75, 100));
        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(187, 197, 187));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "10", "20", "50" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(20, 50, 100))); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        tipoBox.setBackground(new java.awt.Color(70, 75, 100));
        tipoBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tipoBox.setForeground(new java.awt.Color(187, 197, 187));
        tipoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electrodomésticos", "Comida", "Hogar", "Herramienta", "Vestimenta", "Higiene", "Farmacia", "Otros" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Codigo_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Nombre_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Precio_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Marca_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(108, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Cant_Field)
                                .addContainerGap())))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Codigo_Field)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(Nombre_Field))
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cant_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Precio_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Marca_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16))
        );

        RegresarButton.setBackground(new java.awt.Color(90, 0, 0));
        RegresarButton.setFont(new java.awt.Font("Segoe UI Symbol", 0, 28)); // NOI18N
        RegresarButton.setForeground(new java.awt.Color(200, 0, 0));
        RegresarButton.setText("↩");
        RegresarButton.setToolTipText("Regresar");
        RegresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarButtonActionPerformed(evt);
            }
        });

        AyudaButton.setBackground(new java.awt.Color(102, 102, 0));
        AyudaButton.setFont(new java.awt.Font("Segoe UI Symbol", 0, 30)); // NOI18N
        AyudaButton.setForeground(new java.awt.Color(255, 255, 0));
        AyudaButton.setText("?");
        AyudaButton.setToolTipText("Ayuda");
        AyudaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyudaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(406, 406, 406))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(RegresarButton)
                        .addGap(298, 298, 298)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AyudaButton)
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegresarButton)
                    .addComponent(AyudaButton))
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(AceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarButtonActionPerformed
        // TODO add your handling code here:
        Conexion objConexion = new Conexion();
        Data_information objInventario = recuperarDatos();
        if(!error){
            calcula();
            String strSentenciaInsert = String.format("INSERT INTO Inventario (Codigo_Barras,Nombre,Precio,Marca,Fecha_Ingreso,Stock,Tipo,Ventas_Dia,Ventas_Mes,Descuento) "
                + "VALUES ('%d','%s','%.2f','%s','%s','%d','%s','%d','%d','%d')", 
                objInventario.getCodigo_barras(), objInventario.getNombre(), objInventario.getPrecio(), 
                objInventario.getMarca(), fecha, objInventario.getStock(), objInventario.getTipo(), 0, 0, objInventario.getDescuento());
            if(objConexion.ejecutarSentenciaSQL(strSentenciaInsert) == 1)
                JOptionPane.showMessageDialog(null,"Los datos se han insertado correctamente","Insercion",JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog(null,"Error al insertar los datos","Insercion",JOptionPane.ERROR_MESSAGE);
        }
        objConexion.close();
        error = false;
    }//GEN-LAST:event_AceptarButtonActionPerformed

    private void Codigo_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Codigo_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Codigo_FieldActionPerformed

    private void Nombre_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nombre_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nombre_FieldActionPerformed

    private void Marca_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Marca_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Marca_FieldActionPerformed

    private void Precio_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Precio_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Precio_FieldActionPerformed

    private void Cant_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cant_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cant_FieldActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void RegresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_RegresarButtonActionPerformed

    private void AyudaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyudaButtonActionPerformed
        // TODO add your handling code here:
        //textblock
        JOptionPane.showMessageDialog(null, """
            Para registrar un producto se debe de llenar todos los 
            campos, después se debe pulsar el botón aceptar""", "Ayuda", JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_AyudaButtonActionPerformed

    @Override
    public Data_information recuperarDatos(){
        Data_information objInventarios = new Data_information();
        String errMessage="";
        //sacar el codigo de barras
        if(Codigo_Field.getText().isEmpty() || !Codigo_Field.getText().trim().matches("\\d{1,9}"))
            errMessage += " 'Codigo de barras' ";
        else
            objInventarios.setCodigo_barras(Long.parseLong(Codigo_Field.getText()));
        //sacar el nombre
        if(Nombre_Field.getText().isEmpty() || !Nombre_Field.getText().trim().matches("[\\w\\s]{1,100}"))
            errMessage += " 'Nombre' ";
        else
            objInventarios.setNombre(Nombre_Field.getText());
        //sacar el precio
        if(Precio_Field.getText().isEmpty() || !Precio_Field.getText().trim().matches("\\d+(\\.\\d{1,2})?"))
            errMessage += " 'Precio' ";
        else
            objInventarios.setPrecio(Double.parseDouble(Precio_Field.getText()));
        //sacar la marca
        if(Marca_Field.getText().isEmpty() || !Marca_Field.getText().trim().matches("[\\w\\s]{1,50}"))
            errMessage += " 'Marca' ";
        else
            objInventarios.setMarca(Marca_Field.getText());
        //sacar la cantidad/stock
        if(Cant_Field.getText().isEmpty() || !Cant_Field.getText().trim().matches("\\d+"))
            errMessage += " 'Cantidad' ";
        else
            objInventarios.setStock(Integer.parseInt(Cant_Field.getText()));
        //sacar el tipo
        objInventarios.setTipo(tipoBox.getSelectedItem().toString());
        
        //sacar el descuento
        objInventarios.setDescuento(Integer.parseInt(jComboBox1.getSelectedItem().toString()));
        
        if(!errMessage.equals("")){
            JOptionPane.showMessageDialog(null,"Los campos"+errMessage+"se encuentran vacios o son erroneos","Error",JOptionPane.ERROR_MESSAGE);
            error=true;
        }
        return objInventarios;
    }
    
    @Override
    public void run(){
        Thread ct = Thread.currentThread();
        if(ct == hilo){
            calcula();
        }
    }
    
    private void calcula(){
        Calendar calendario = new GregorianCalendar();
        Date fechaActual = new Date();
        calendario.setTime(fechaActual);
        dia = calendario.get(Calendar.DAY_OF_MONTH);
        mes = calendario.get(Calendar.MONTH) + 1;       //el mes marca un numero menor
        anio = calendario.get(Calendar.YEAR);
        if(dia < 10){
            if(mes < 10)
                fecha = String.format("%d-0%d-0%d", anio,mes,dia);  //si el dia y el mes son menores que 10
            else
                fecha = String.format("%d-%d-0%d", anio,mes,dia);       //si SOLO el dia es menor que 10
        }
        else{
            if(mes < 10)
                fecha = String.format("%d-0%d-%d", anio,mes,dia);  //si SOLO el mes es menor que 10
            else
                fecha = String.format("%d-%d-%d", anio,mes,dia);       //si NINGUNO es menor que 10
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarButton;
    private javax.swing.JButton AyudaButton;
    private javax.swing.JTextField Cant_Field;
    private javax.swing.JTextField Codigo_Field;
    private javax.swing.JTextField Marca_Field;
    private javax.swing.JTextField Nombre_Field;
    private javax.swing.JTextField Precio_Field;
    private javax.swing.JButton RegresarButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> tipoBox;
    // End of variables declaration//GEN-END:variables
}
