/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadoraframe;

/**
 *
 * @author josel
 */
public class Calculadora2024 extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora2024
     */
    double num1,num2;
    String signo;
    
    public Calculadora2024() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Display = new javax.swing.JLabel();
        jButton_Clear = new javax.swing.JButton();
        jButton_Times = new javax.swing.JButton();
        jButton_Minus = new javax.swing.JButton();
        jButton_Division = new javax.swing.JButton();
        jButton_9 = new javax.swing.JButton();
        jButton_8 = new javax.swing.JButton();
        jButton_7 = new javax.swing.JButton();
        jButton_6 = new javax.swing.JButton();
        jButton_3 = new javax.swing.JButton();
        jButton_Plus = new javax.swing.JButton();
        jButton_Equal = new javax.swing.JButton();
        jButton_5 = new javax.swing.JButton();
        jButton_2 = new javax.swing.JButton();
        jButton_1 = new javax.swing.JButton();
        jButton_4 = new javax.swing.JButton();
        jButton_0 = new javax.swing.JButton();
        jButton_Point = new javax.swing.JButton();
        jButton_Minus1 = new javax.swing.JButton();
        jButton_Times1 = new javax.swing.JButton();
        jButton_Division1 = new javax.swing.JButton();
        jButton_Clear1 = new javax.swing.JButton();
        jButton_Clear2 = new javax.swing.JButton();
        jButton_Times2 = new javax.swing.JButton();
        jButton_Division2 = new javax.swing.JButton();
        jButton_Clear3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(40, 5, 50));

        Display.setBackground(new java.awt.Color(20, 10, 10));
        Display.setFont(new java.awt.Font("Cambria Math", 1, 28)); // NOI18N
        Display.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Display.setText("0");
        Display.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Display.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, new java.awt.Color(102, 0, 102)));
        Display.setOpaque(true);

        jButton_Clear.setBackground(new java.awt.Color(150, 150, 150));
        jButton_Clear.setFont(new java.awt.Font("Lucida Console", 1, 20)); // NOI18N
        jButton_Clear.setForeground(new java.awt.Color(150, 60, 60));
        jButton_Clear.setText("C");
        jButton_Clear.setBorder(null);
        jButton_Clear.setBorderPainted(false);
        jButton_Clear.setOpaque(true);
        jButton_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClearActionPerformed(evt);
            }
        });

        jButton_Times.setBackground(new java.awt.Color(150, 150, 150));
        jButton_Times.setFont(new java.awt.Font("Lucida Console", 1, 20)); // NOI18N
        jButton_Times.setForeground(new java.awt.Color(60, 60, 60));
        jButton_Times.setText("*");
        jButton_Times.setBorder(null);
        jButton_Times.setBorderPainted(false);
        jButton_Times.setOpaque(true);
        jButton_Times.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TimesActionPerformed(evt);
            }
        });

        jButton_Minus.setBackground(new java.awt.Color(150, 150, 150));
        jButton_Minus.setFont(new java.awt.Font("Lucida Console", 1, 20)); // NOI18N
        jButton_Minus.setForeground(new java.awt.Color(60, 60, 60));
        jButton_Minus.setText("-");
        jButton_Minus.setBorder(null);
        jButton_Minus.setBorderPainted(false);
        jButton_Minus.setOpaque(true);
        jButton_Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MinusActionPerformed(evt);
            }
        });

        jButton_Division.setBackground(new java.awt.Color(150, 150, 150));
        jButton_Division.setFont(new java.awt.Font("Lucida Console", 1, 20)); // NOI18N
        jButton_Division.setForeground(new java.awt.Color(60, 60, 60));
        jButton_Division.setText("/");
        jButton_Division.setBorder(null);
        jButton_Division.setBorderPainted(false);
        jButton_Division.setOpaque(true);
        jButton_Division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DivisionActionPerformed(evt);
            }
        });

        jButton_9.setBackground(new java.awt.Color(50, 50, 50));
        jButton_9.setFont(new java.awt.Font("Lucida Console", 1, 20)); // NOI18N
        jButton_9.setForeground(new java.awt.Color(160, 160, 160));
        jButton_9.setText("9");
        jButton_9.setBorder(null);
        jButton_9.setBorderPainted(false);
        jButton_9.setOpaque(true);
        jButton_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_9ActionPerformed(evt);
            }
        });

        jButton_8.setBackground(new java.awt.Color(50, 50, 50));
        jButton_8.setFont(new java.awt.Font("Lucida Console", 1, 20)); // NOI18N
        jButton_8.setForeground(new java.awt.Color(160, 160, 160));
        jButton_8.setText("8");
        jButton_8.setBorder(null);
        jButton_8.setBorderPainted(false);
        jButton_8.setOpaque(true);
        jButton_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_8ActionPerformed(evt);
            }
        });

        jButton_7.setBackground(new java.awt.Color(50, 50, 50));
        jButton_7.setFont(new java.awt.Font("Lucida Console", 1, 20)); // NOI18N
        jButton_7.setForeground(new java.awt.Color(160, 160, 160));
        jButton_7.setText("7");
        jButton_7.setBorder(null);
        jButton_7.setBorderPainted(false);
        jButton_7.setOpaque(true);
        jButton_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_7ActionPerformed(evt);
            }
        });

        jButton_6.setBackground(new java.awt.Color(50, 50, 50));
        jButton_6.setFont(new java.awt.Font("Lucida Console", 1, 20)); // NOI18N
        jButton_6.setForeground(new java.awt.Color(160, 160, 160));
        jButton_6.setText("6");
        jButton_6.setBorder(null);
        jButton_6.setBorderPainted(false);
        jButton_6.setOpaque(true);
        jButton_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_6ActionPerformed(evt);
            }
        });

        jButton_3.setBackground(new java.awt.Color(50, 50, 50));
        jButton_3.setFont(new java.awt.Font("Lucida Console", 1, 20)); // NOI18N
        jButton_3.setForeground(new java.awt.Color(160, 160, 160));
        jButton_3.setText("3");
        jButton_3.setBorder(null);
        jButton_3.setBorderPainted(false);
        jButton_3.setOpaque(true);
        jButton_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_3ActionPerformed(evt);
            }
        });

        jButton_Plus.setBackground(new java.awt.Color(150, 150, 150));
        jButton_Plus.setFont(new java.awt.Font("Lucida Console", 1, 20)); // NOI18N
        jButton_Plus.setForeground(new java.awt.Color(60, 60, 60));
        jButton_Plus.setText("+");
        jButton_Plus.setBorder(null);
        jButton_Plus.setBorderPainted(false);
        jButton_Plus.setOpaque(true);
        jButton_Plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PlusActionPerformed(evt);
            }
        });

        jButton_Equal.setBackground(new java.awt.Color(150, 150, 150));
        jButton_Equal.setFont(new java.awt.Font("Lucida Console", 1, 20)); // NOI18N
        jButton_Equal.setForeground(new java.awt.Color(60, 60, 60));
        jButton_Equal.setText("=");
        jButton_Equal.setBorder(null);
        jButton_Equal.setBorderPainted(false);
        jButton_Equal.setOpaque(true);
        jButton_Equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EqualActionPerformed(evt);
            }
        });

        jButton_5.setBackground(new java.awt.Color(50, 50, 50));
        jButton_5.setFont(new java.awt.Font("Lucida Console", 1, 20)); // NOI18N
        jButton_5.setForeground(new java.awt.Color(160, 160, 160));
        jButton_5.setText("5");
        jButton_5.setBorder(null);
        jButton_5.setBorderPainted(false);
        jButton_5.setOpaque(true);
        jButton_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_5ActionPerformed(evt);
            }
        });

        jButton_2.setBackground(new java.awt.Color(50, 50, 50));
        jButton_2.setFont(new java.awt.Font("Lucida Console", 1, 20)); // NOI18N
        jButton_2.setForeground(new java.awt.Color(160, 160, 160));
        jButton_2.setText("2");
        jButton_2.setBorder(null);
        jButton_2.setBorderPainted(false);
        jButton_2.setOpaque(true);
        jButton_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_2ActionPerformed(evt);
            }
        });

        jButton_1.setBackground(new java.awt.Color(50, 50, 50));
        jButton_1.setFont(new java.awt.Font("Lucida Console", 1, 20)); // NOI18N
        jButton_1.setForeground(new java.awt.Color(160, 160, 160));
        jButton_1.setText("1");
        jButton_1.setBorder(null);
        jButton_1.setBorderPainted(false);
        jButton_1.setOpaque(true);
        jButton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_1ActionPerformed(evt);
            }
        });

        jButton_4.setBackground(new java.awt.Color(50, 50, 50));
        jButton_4.setFont(new java.awt.Font("Lucida Console", 1, 20)); // NOI18N
        jButton_4.setForeground(new java.awt.Color(160, 160, 160));
        jButton_4.setText("4");
        jButton_4.setBorder(null);
        jButton_4.setBorderPainted(false);
        jButton_4.setOpaque(true);
        jButton_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_4ActionPerformed(evt);
            }
        });

        jButton_0.setBackground(new java.awt.Color(50, 50, 50));
        jButton_0.setFont(new java.awt.Font("Lucida Console", 1, 20)); // NOI18N
        jButton_0.setForeground(new java.awt.Color(160, 160, 160));
        jButton_0.setText("0");
        jButton_0.setBorder(null);
        jButton_0.setBorderPainted(false);
        jButton_0.setOpaque(true);
        jButton_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_0ActionPerformed(evt);
            }
        });

        jButton_Point.setBackground(new java.awt.Color(50, 50, 50));
        jButton_Point.setFont(new java.awt.Font("Lucida Console", 1, 20)); // NOI18N
        jButton_Point.setForeground(new java.awt.Color(160, 160, 160));
        jButton_Point.setText(".");
        jButton_Point.setBorder(null);
        jButton_Point.setBorderPainted(false);
        jButton_Point.setOpaque(true);
        jButton_Point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PointActionPerformed(evt);
            }
        });

        jButton_Minus1.setBackground(new java.awt.Color(150, 150, 150));
        jButton_Minus1.setFont(new java.awt.Font("Lucida Console", 1, 20)); // NOI18N
        jButton_Minus1.setForeground(new java.awt.Color(60, 60, 60));
        jButton_Minus1.setText("tan");
        jButton_Minus1.setBorder(null);
        jButton_Minus1.setBorderPainted(false);
        jButton_Minus1.setOpaque(true);
        jButton_Minus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Minus1ActionPerformed(evt);
            }
        });

        jButton_Times1.setBackground(new java.awt.Color(150, 150, 150));
        jButton_Times1.setFont(new java.awt.Font("Lucida Console", 1, 20)); // NOI18N
        jButton_Times1.setForeground(new java.awt.Color(60, 60, 60));
        jButton_Times1.setText("cos");
        jButton_Times1.setBorder(null);
        jButton_Times1.setBorderPainted(false);
        jButton_Times1.setOpaque(true);
        jButton_Times1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Times1ActionPerformed(evt);
            }
        });

        jButton_Division1.setBackground(new java.awt.Color(150, 150, 150));
        jButton_Division1.setFont(new java.awt.Font("Lucida Console", 1, 20)); // NOI18N
        jButton_Division1.setForeground(new java.awt.Color(60, 60, 60));
        jButton_Division1.setText("sin");
        jButton_Division1.setBorder(null);
        jButton_Division1.setBorderPainted(false);
        jButton_Division1.setOpaque(true);
        jButton_Division1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Division1ActionPerformed(evt);
            }
        });

        jButton_Clear1.setBackground(new java.awt.Color(150, 150, 150));
        jButton_Clear1.setFont(new java.awt.Font("Lucida Console", 1, 20)); // NOI18N
        jButton_Clear1.setForeground(new java.awt.Color(60, 60, 60));
        jButton_Clear1.setText("√");
        jButton_Clear1.setBorder(null);
        jButton_Clear1.setBorderPainted(false);
        jButton_Clear1.setOpaque(true);
        jButton_Clear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Clear1ActionPerformed(evt);
            }
        });

        jButton_Clear2.setBackground(new java.awt.Color(150, 150, 150));
        jButton_Clear2.setFont(new java.awt.Font("Cambria Math", 1, 20)); // NOI18N
        jButton_Clear2.setForeground(new java.awt.Color(60, 60, 60));
        jButton_Clear2.setText("□²");
        jButton_Clear2.setBorder(null);
        jButton_Clear2.setBorderPainted(false);
        jButton_Clear2.setOpaque(true);
        jButton_Clear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Clear2ActionPerformed(evt);
            }
        });

        jButton_Times2.setBackground(new java.awt.Color(150, 150, 150));
        jButton_Times2.setFont(new java.awt.Font("Lucida Console", 1, 20)); // NOI18N
        jButton_Times2.setForeground(new java.awt.Color(60, 60, 60));
        jButton_Times2.setText("x10");
        jButton_Times2.setBorder(null);
        jButton_Times2.setBorderPainted(false);
        jButton_Times2.setOpaque(true);
        jButton_Times2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Times2ActionPerformed(evt);
            }
        });

        jButton_Division2.setBackground(new java.awt.Color(150, 150, 150));
        jButton_Division2.setFont(new java.awt.Font("Cambria Math", 1, 20)); // NOI18N
        jButton_Division2.setForeground(new java.awt.Color(60, 60, 60));
        jButton_Division2.setText("π");
        jButton_Division2.setBorder(null);
        jButton_Division2.setBorderPainted(false);
        jButton_Division2.setOpaque(true);
        jButton_Division2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Division2ActionPerformed(evt);
            }
        });

        jButton_Clear3.setBackground(new java.awt.Color(150, 150, 150));
        jButton_Clear3.setFont(new java.awt.Font("Lucida Console", 1, 20)); // NOI18N
        jButton_Clear3.setForeground(new java.awt.Color(60, 60, 60));
        jButton_Clear3.setText("!");
        jButton_Clear3.setBorder(null);
        jButton_Clear3.setBorderPainted(false);
        jButton_Clear3.setOpaque(true);
        jButton_Clear3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Clear3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton_7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(38, 38, 38)
                                    .addComponent(jButton_8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButton_4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(38, 38, 38))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jButton_1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton_5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jButton_0, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton_3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(93, 93, 93))
                                .addComponent(jButton_6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton_Clear2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_Clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(38, 38, 38)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton_Division1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_Division, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton_Times, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(38, 38, 38)
                                    .addComponent(jButton_Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton_Times1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(38, 38, 38)
                                    .addComponent(jButton_Minus1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton_Clear3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(jButton_Division2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Times2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(jButton_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton_Plus, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_Point, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButton_Equal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Display, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Times2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_Division2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_Clear3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Minus1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Times1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Division1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Clear1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Times, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Clear2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton_Plus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_0, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Point, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton_Equal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClearActionPerformed
        // TODO add your handling code here:
        Display.setText("0");
    }//GEN-LAST:event_jButton_ClearActionPerformed

    private void jButton_TimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TimesActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(Display.getText());
        signo = "*";
        Display.setText("");
    }//GEN-LAST:event_jButton_TimesActionPerformed

    private void jButton_MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MinusActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(Display.getText());
        signo = "-";
        Display.setText("");
    }//GEN-LAST:event_jButton_MinusActionPerformed

    private void jButton_DivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DivisionActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(Display.getText());
        signo = "/";
        Display.setText("");
        
    }//GEN-LAST:event_jButton_DivisionActionPerformed

    private void jButton_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_9ActionPerformed
        // TODO add your handling code here:
        if (Display.getText()=="0")
            Display.setText("9");
        else
            Display.setText(Display.getText()+"9");
    }//GEN-LAST:event_jButton_9ActionPerformed

    private void jButton_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_8ActionPerformed
        // TODO add your handling code here:
        if (Display.getText()=="0")
            Display.setText("8");
        else
            Display.setText(Display.getText()+"8");
    }//GEN-LAST:event_jButton_8ActionPerformed

    private void jButton_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_7ActionPerformed
        // TODO add your handling code here:
        if (Display.getText()=="0")
            Display.setText("7");
        else
            Display.setText(Display.getText()+"7");
    }//GEN-LAST:event_jButton_7ActionPerformed

    private void jButton_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_6ActionPerformed
        // TODO add your handling code here:
        if (Display.getText()=="0")
            Display.setText("6");
        else
            Display.setText(Display.getText()+"6");
    }//GEN-LAST:event_jButton_6ActionPerformed

    private void jButton_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_3ActionPerformed
        // TODO add your handling code here:
        if (Display.getText()=="0")
            Display.setText("3");
        else
            Display.setText(Display.getText()+"3");
    }//GEN-LAST:event_jButton_3ActionPerformed

    private void jButton_PlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PlusActionPerformed
        // TODO add your handling code here:
        num1 = Double.parseDouble(Display.getText());
        signo = "+";
        Display.setText("");
    }//GEN-LAST:event_jButton_PlusActionPerformed

    private void jButton_EqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EqualActionPerformed
        // TODO add your handling code here:
        num2 = Double.parseDouble(Display.getText());
        
        switch(signo)
        {
            case "+":
                Display.setText(Double.toString(num1+num2));
                break;
            case "-":
                Display.setText(Double.toString(num1-num2));
                break;
            case "/":
                Display.setText(Double.toString(num1/num2));
                break;
            case "*":
                Display.setText(Double.toString(num1*num2));
                break;
        }
    }//GEN-LAST:event_jButton_EqualActionPerformed

    private void jButton_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_5ActionPerformed
        // TODO add your handling code here:
        if (Display.getText()=="0")
            Display.setText("5");
        else
            Display.setText(Display.getText()+"5");
    }//GEN-LAST:event_jButton_5ActionPerformed

    private void jButton_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_2ActionPerformed
        // TODO add your handling code here:
        if (Display.getText()=="0")
            Display.setText("2");
        else
            Display.setText(Display.getText()+"2");
    }//GEN-LAST:event_jButton_2ActionPerformed

    private void jButton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_1ActionPerformed
        // TODO add your handling code here:
        if (Display.getText()=="0")
            Display.setText("1");
        else
            Display.setText(Display.getText()+"1");
    }//GEN-LAST:event_jButton_1ActionPerformed

    private void jButton_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_4ActionPerformed
        if (Display.getText()=="0")
            Display.setText("4");
        else
            Display.setText(Display.getText()+"4");
    }//GEN-LAST:event_jButton_4ActionPerformed

    private void jButton_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_0ActionPerformed
        if (Display.getText()=="0")
            Display.setText("0");
        else
            Display.setText(Display.getText()+"0");
    }//GEN-LAST:event_jButton_0ActionPerformed

    private void jButton_PointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PointActionPerformed
        // TODO add your handling code here:
        if (!(this.Display.getText().contains(".")))
        {
            this.Display.setText(this.Display.getText()+".");
        }
    }//GEN-LAST:event_jButton_PointActionPerformed

    private void jButton_Minus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Minus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Minus1ActionPerformed

    private void jButton_Times1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Times1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Times1ActionPerformed

    private void jButton_Division1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Division1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Division1ActionPerformed

    private void jButton_Clear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Clear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Clear1ActionPerformed

    private void jButton_Clear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Clear2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Clear2ActionPerformed

    private void jButton_Times2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Times2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Times2ActionPerformed

    private void jButton_Division2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Division2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Division2ActionPerformed

    private void jButton_Clear3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Clear3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Clear3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora2024.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora2024.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora2024.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora2024.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora2024().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Display;
    private javax.swing.JButton jButton_0;
    private javax.swing.JButton jButton_1;
    private javax.swing.JButton jButton_2;
    private javax.swing.JButton jButton_3;
    private javax.swing.JButton jButton_4;
    private javax.swing.JButton jButton_5;
    private javax.swing.JButton jButton_6;
    private javax.swing.JButton jButton_7;
    private javax.swing.JButton jButton_8;
    private javax.swing.JButton jButton_9;
    private javax.swing.JButton jButton_Clear;
    private javax.swing.JButton jButton_Clear1;
    private javax.swing.JButton jButton_Clear2;
    private javax.swing.JButton jButton_Clear3;
    private javax.swing.JButton jButton_Division;
    private javax.swing.JButton jButton_Division1;
    private javax.swing.JButton jButton_Division2;
    private javax.swing.JButton jButton_Equal;
    private javax.swing.JButton jButton_Minus;
    private javax.swing.JButton jButton_Minus1;
    private javax.swing.JButton jButton_Plus;
    private javax.swing.JButton jButton_Point;
    private javax.swing.JButton jButton_Times;
    private javax.swing.JButton jButton_Times1;
    private javax.swing.JButton jButton_Times2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
