/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventario;

import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import setConection.Conexion;

/**
 *
 * @author easyb
 */
public class Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Consultas
     */
    
    DefaultTableModel modelo;
    
    public Consultas() {
        initComponents();
        this.setLocationRelativeTo(null);
        String[] titulos={"Codigo de Barras","Nombre","Precio","Marca","Fecha de Ingreso","Stock","Tipo","Ventas del dia","Ventas del mes"};
        modelo = new DefaultTableModel(null, titulos);
        tablaConsultas.setModel(modelo);
        
        diaSpinner.getEditor().getComponent(0).setBackground(new Color(57,73,75));
        diaSpinner.getEditor().getComponent(0).setForeground(new Color(187,197,207));
        mesSpinner.getEditor().getComponent(0).setBackground(new Color(57,73,75));
        mesSpinner.getEditor().getComponent(0).setForeground(new Color(187,197,207));
        yearSpinner.getEditor().getComponent(0).setBackground(new Color(57,73,75));
        yearSpinner.getEditor().getComponent(0).setForeground(new Color(187,197,207));
       
        primerValor.getEditor().getComponent(0).setBackground(new Color(57,73,75));
        primerValor.getEditor().getComponent(0).setForeground(new Color(187,197,207));
        segundoValor.getEditor().getComponent(0).setBackground(new Color(57,73,75));
        segundoValor.getEditor().getComponent(0).setForeground(new Color(187,197,207));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConsultas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        consultaGeneralBoton = new javax.swing.JButton();
        ventasDiaBoton = new javax.swing.JButton();
        ventasMesBoton = new javax.swing.JButton();
        codigoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codigo_Field = new javax.swing.JTextField();
        codigoBoton = new javax.swing.JButton();
        tipoPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tipoBoton = new javax.swing.JButton();
        tipoBox = new javax.swing.JComboBox<>();
        fechaPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        diaSpinner = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        mesSpinner = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        yearSpinner = new javax.swing.JSpinner();
        fechaBoton = new javax.swing.JButton();
        costoPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        primerValor = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        segundoValor = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        ordenarPor = new javax.swing.JComboBox<>();
        costosBoton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        RegresarButton = new javax.swing.JButton();
        AyudaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultas");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(110, 140, 100));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 0));
        jLabel2.setText("CONSULTAS");

        tablaConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código de Barras", "Nombre", "Precio", "Marca", "Fecha de ingreso", "Stock", "Tipo", "Ventas día", "Ventas mes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaConsultas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaConsultas);

        jPanel2.setBackground(new java.awt.Color(100, 110, 130));

        consultaGeneralBoton.setBackground(new java.awt.Color(70, 75, 90));
        consultaGeneralBoton.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        consultaGeneralBoton.setForeground(new java.awt.Color(60, 251, 83));
        consultaGeneralBoton.setText("CONSULTA SIN PARAMETROS");
        consultaGeneralBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaGeneralBotonActionPerformed(evt);
            }
        });

        ventasDiaBoton.setBackground(new java.awt.Color(70, 75, 90));
        ventasDiaBoton.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        ventasDiaBoton.setForeground(new java.awt.Color(60, 251, 83));
        ventasDiaBoton.setText("CONSULTAR VENTAS DEL DIA");
        ventasDiaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasDiaBotonActionPerformed(evt);
            }
        });

        ventasMesBoton.setBackground(new java.awt.Color(70, 75, 90));
        ventasMesBoton.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        ventasMesBoton.setForeground(new java.awt.Color(60, 251, 83));
        ventasMesBoton.setText("CONSULTAR VENTAS DEL MES");
        ventasMesBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasMesBotonActionPerformed(evt);
            }
        });

        codigoPanel.setBackground(new java.awt.Color(28, 63, 65));

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("Codigo de Barras:");

        codigo_Field.setBackground(new java.awt.Color(57, 73, 75));
        codigo_Field.setForeground(new java.awt.Color(187, 197, 207));
        codigo_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigo_FieldActionPerformed(evt);
            }
        });

        codigoBoton.setBackground(new java.awt.Color(70, 75, 90));
        codigoBoton.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        codigoBoton.setForeground(new java.awt.Color(120, 231, 113));
        codigoBoton.setText("CONSULTAR");
        codigoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout codigoPanelLayout = new javax.swing.GroupLayout(codigoPanel);
        codigoPanel.setLayout(codigoPanelLayout);
        codigoPanelLayout.setHorizontalGroup(
            codigoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, codigoPanelLayout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addComponent(codigo_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(codigoBoton)
                .addGap(20, 20, 20))
            .addGroup(codigoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(codigoPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(369, Short.MAX_VALUE)))
        );
        codigoPanelLayout.setVerticalGroup(
            codigoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(codigoPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(codigoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(codigo_Field)
                    .addComponent(codigoBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(codigoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(codigoPanelLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(jLabel1)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );

        tipoPanel.setBackground(new java.awt.Color(28, 63, 65));

        jLabel7.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 51));
        jLabel7.setText("Tipo:");

        tipoBoton.setBackground(new java.awt.Color(70, 75, 90));
        tipoBoton.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        tipoBoton.setForeground(new java.awt.Color(120, 231, 113));
        tipoBoton.setText("CONSULTAR");
        tipoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoBotonActionPerformed(evt);
            }
        });

        tipoBox.setBackground(new java.awt.Color(57, 73, 75));
        tipoBox.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tipoBox.setForeground(new java.awt.Color(187, 197, 207));
        tipoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electrodomésticos", "Comida", "Hogar", "Herramienta", "Vestimenta", "Higiene", "Farmacia", "Otros" }));

        javax.swing.GroupLayout tipoPanelLayout = new javax.swing.GroupLayout(tipoPanel);
        tipoPanel.setLayout(tipoPanelLayout);
        tipoPanelLayout.setHorizontalGroup(
            tipoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tipoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(tipoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(tipoBoton)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        tipoPanelLayout.setVerticalGroup(
            tipoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tipoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tipoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tipoPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        fechaPanel.setBackground(new java.awt.Color(28, 63, 65));

        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 51));
        jLabel6.setText("Fecha:  día");

        diaSpinner.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        diaSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        diaSpinner.setOpaque(true);

        jLabel13.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 255, 51));
        jLabel13.setText("mes");

        mesSpinner.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        mesSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        jLabel14.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 255, 51));
        jLabel14.setText("año");

        yearSpinner.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        yearSpinner.setModel(new javax.swing.SpinnerNumberModel(1970, 1970, 2999, 1));

        fechaBoton.setBackground(new java.awt.Color(70, 75, 90));
        fechaBoton.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        fechaBoton.setForeground(new java.awt.Color(120, 231, 113));
        fechaBoton.setText("CONSULTAR");
        fechaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fechaPanelLayout = new javax.swing.GroupLayout(fechaPanel);
        fechaPanel.setLayout(fechaPanelLayout);
        fechaPanelLayout.setHorizontalGroup(
            fechaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fechaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(yearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fechaBoton)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        fechaPanelLayout.setVerticalGroup(
            fechaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fechaPanelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(fechaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fechaPanelLayout.createSequentialGroup()
                        .addGroup(fechaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fechaPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(fechaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel14)
                            .addGroup(fechaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(diaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13))
                            .addComponent(fechaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
        );

        costoPanel.setBackground(new java.awt.Color(28, 63, 65));

        jLabel8.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 51));
        jLabel8.setText("Costos:   desde");

        primerValor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        primerValor.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.01f));

        jLabel12.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 255, 51));
        jLabel12.setText("hasta");

        segundoValor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        segundoValor.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.01f));

        jLabel10.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 51));
        jLabel10.setText("Ordenar");

        ordenarPor.setBackground(new java.awt.Color(57, 73, 75));
        ordenarPor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ordenarPor.setForeground(new java.awt.Color(187, 197, 207));
        ordenarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mayor", "Menor" }));
        ordenarPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarPorActionPerformed(evt);
            }
        });

        costosBoton.setBackground(new java.awt.Color(70, 75, 90));
        costosBoton.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        costosBoton.setForeground(new java.awt.Color(120, 231, 113));
        costosBoton.setText("CONSULTAR");
        costosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costosBotonActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(100, 110, 130));
        jSeparator1.setForeground(new java.awt.Color(100, 110, 130));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout costoPanelLayout = new javax.swing.GroupLayout(costoPanel);
        costoPanel.setLayout(costoPanelLayout);
        costoPanelLayout.setHorizontalGroup(
            costoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(costoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(primerValor, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(segundoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ordenarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(costosBoton)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        costoPanelLayout.setVerticalGroup(
            costoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(costoPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(costoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(costoPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(costoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(primerValor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(segundoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(costoPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(costoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ordenarPor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costosBoton)))
                    .addGroup(costoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel8)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(costoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ventasMesBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(consultaGeneralBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                        .addComponent(ventasDiaBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(codigoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(ventasDiaBoton)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fechaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ventasMesBoton)
                        .addGap(79, 79, 79)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(costoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultaGeneralBoton))
                .addGap(10, 10, 10))
        );

        RegresarButton.setBackground(new java.awt.Color(90, 0, 0));
        RegresarButton.setFont(new java.awt.Font("Segoe UI Symbol", 0, 28)); // NOI18N
        RegresarButton.setForeground(new java.awt.Color(200, 0, 0));
        RegresarButton.setText("↩");
        RegresarButton.setToolTipText("Regresar");
        RegresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarButtonActionPerformed(evt);
            }
        });

        AyudaButton.setBackground(new java.awt.Color(102, 102, 0));
        AyudaButton.setFont(new java.awt.Font("Segoe UI Symbol", 0, 30)); // NOI18N
        AyudaButton.setForeground(new java.awt.Color(255, 255, 0));
        AyudaButton.setText("?");
        AyudaButton.setToolTipText("Ayuda");
        AyudaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyudaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(RegresarButton)
                .addGap(437, 437, 437)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AyudaButton)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(RegresarButton)
                    .addComponent(AyudaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigo_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigo_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigo_FieldActionPerformed

    private void codigoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoBotonActionPerformed
        // TODO add your handling code here:
        //evalua si el codigo de barras es numerico
        Conexion objConexion = new Conexion();
        String strSentenciaInsert = String.format("SELECT * FROM Inventario WHERE Codigo_Barras=%s",codigo_Field.getText());
        if(objConexion.ejecutarSentenciaSQL(strSentenciaInsert) == 1){
            while(modelo.getRowCount()>0)
                modelo.removeRow(0);
            try{
                ResultSet resultado=objConexion.consultarRegistro("SELECT * FROM Inventario WHERE Codigo_Barras="+codigo_Field.getText());
                while(resultado.next()){
                    Object[] objUsuario = {resultado.getString("Codigo_Barras"), resultado.getString("Nombre"), 
                        resultado.getString("Precio"), resultado.getString("Marca"), resultado.getString("Fecha_Ingreso"), 
                        resultado.getString("Stock"), resultado.getString("Tipo"), resultado.getString("Ventas_Dia"), resultado.getString("Ventas_Mes")};
                    modelo.addRow(objUsuario);
                }
            }catch(Exception e){
                System.out.println("Error de consulta "+e);
            }
        }else
            JOptionPane.showMessageDialog(null, "El campo debe de contener numeros", "Error", JOptionPane.ERROR_MESSAGE);
        objConexion.close();
    }//GEN-LAST:event_codigoBotonActionPerformed

    private void tipoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoBotonActionPerformed
        // TODO add your handling code here:
        Conexion objConexion = new Conexion();
        String strSentenciaInsert = String.format("SELECT * FROM Inventario WHERE Tipo='%s'",tipoBox.getSelectedItem());
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        while(modelo.getRowCount()>0)
            modelo.removeRow(0);
        try{
            ResultSet resultado=objConexion.consultarRegistro("SELECT * FROM Inventario WHERE Tipo='"+tipoBox.getSelectedItem()+"'");
            while(resultado.next()){
                Object[] objUsuario = {resultado.getString("Codigo_Barras"), resultado.getString("Nombre"), 
                    resultado.getString("Precio"), resultado.getString("Marca"), resultado.getString("Fecha_Ingreso"), 
                    resultado.getString("Stock"), resultado.getString("Tipo"), resultado.getString("Ventas_Dia"), resultado.getString("Ventas_Mes")};
                modelo.addRow(objUsuario);
            }
        }catch(Exception e){
            System.out.println("Error de consulta "+e);
        }
        objConexion.close();
    }//GEN-LAST:event_tipoBotonActionPerformed

    private void fechaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaBotonActionPerformed
        // TODO add your handling code here:
        Conexion objConexion = new Conexion();
        String strSentenciaInsert = String.format("SELECT * FROM Inventario WHERE Fecha_Ingreso='%s-%s-%s'",
                yearSpinner.getValue(),Integer.parseInt(mesSpinner.getValue().toString())<10?"0"+mesSpinner.getValue():mesSpinner.getValue(),
                Integer.parseInt(diaSpinner.getValue().toString())<10?"0"+diaSpinner.getValue():diaSpinner.getValue());
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        while(modelo.getRowCount()>0)
            modelo.removeRow(0);
        try{
            ResultSet resultado=objConexion.consultarRegistro("SELECT * FROM Inventario WHERE Fecha_Ingreso='"+yearSpinner.getValue()
                    +"-"+(Integer.parseInt(mesSpinner.getValue().toString())<10?"0"+mesSpinner.getValue():mesSpinner.getValue())
                    +"-"+(Integer.parseInt(diaSpinner.getValue().toString())<10?"0"+diaSpinner.getValue():diaSpinner.getValue())+"'");
            while(resultado.next()){
                Object[] objUsuario = {resultado.getString("Codigo_Barras"), resultado.getString("Nombre"), 
                    resultado.getString("Precio"), resultado.getString("Marca"), resultado.getString("Fecha_Ingreso"), 
                    resultado.getString("Stock"), resultado.getString("Tipo"), resultado.getString("Ventas_Dia"), resultado.getString("Ventas_Mes")};
                modelo.addRow(objUsuario);
            }
        }catch(Exception e){
            System.out.println("Error de consulta "+e);
        }
        objConexion.close();
    }//GEN-LAST:event_fechaBotonActionPerformed

    private void ventasDiaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasDiaBotonActionPerformed
        // TODO add your handling code here:
        Conexion objConexion = new Conexion();
        String strSentenciaInsert = String.format("SELECT * FROM Inventario WHERE Ventas_Dia>0 ORDER BY Ventas_Dia DESC");
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        while(modelo.getRowCount()>0)
            modelo.removeRow(0);
        try{
            ResultSet resultado=objConexion.consultarRegistro("SELECT * FROM Inventario WHERE Ventas_Dia>0 ORDER BY Ventas_Dia DESC");
            while(resultado.next()){
                Object[] objUsuario = {resultado.getString("Codigo_Barras"), resultado.getString("Nombre"), 
                    resultado.getString("Precio"), resultado.getString("Marca"), resultado.getString("Fecha_Ingreso"), 
                    resultado.getString("Stock"), resultado.getString("Tipo"), resultado.getString("Ventas_Dia"), resultado.getString("Ventas_Mes")};
                modelo.addRow(objUsuario);
            }
        }catch(Exception e){
            System.out.println("Error de consulta "+e);
        }
        objConexion.close();
    }//GEN-LAST:event_ventasDiaBotonActionPerformed

    private void ventasMesBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasMesBotonActionPerformed
        // TODO add your handling code here:
        Conexion objConexion = new Conexion();
        String strSentenciaInsert = String.format("SELECT * FROM Inventario WHERE Ventas_Mes>0 ORDER BY Ventas_Mes DESC");
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        while(modelo.getRowCount()>0)
            modelo.removeRow(0);
        try{
            ResultSet resultado=objConexion.consultarRegistro("SELECT * FROM Inventario WHERE Ventas_Mes>0 ORDER BY Ventas_Mes DESC");
            while(resultado.next()){
                Object[] objUsuario = {resultado.getString("Codigo_Barras"), resultado.getString("Nombre"), 
                    resultado.getString("Precio"), resultado.getString("Marca"), resultado.getString("Fecha_Ingreso"), 
                    resultado.getString("Stock"), resultado.getString("Tipo"), resultado.getString("Ventas_Dia"), resultado.getString("Ventas_Mes")};
                modelo.addRow(objUsuario);
            }
        }catch(Exception e){
            System.out.println("Error de consulta "+e);
        }
        objConexion.close();
    }//GEN-LAST:event_ventasMesBotonActionPerformed

    private void costosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costosBotonActionPerformed
        // TODO add your handling code here:
        Conexion objConexion = new Conexion();
        String strSentenciaInsert;
        if(ordenarPor.getSelectedItem().equals("Mayor"))
            strSentenciaInsert = String.format("SELECT * FROM Inventario WHERE Precio BETWEEN %s AND %s ORDER BY Precio",primerValor.getValue(),segundoValor.getValue());
        else
            strSentenciaInsert = String.format("SELECT * FROM Inventario WHERE Precio BETWEEN %s AND %s ORDER BY Precio DESC",primerValor.getValue(),segundoValor.getValue());
        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
        while(modelo.getRowCount()>0)
            modelo.removeRow(0);
        try{
            ResultSet resultado=null;
            if(ordenarPor.getSelectedItem().equals("Mayor"))
                resultado=objConexion.consultarRegistro("SELECT * FROM Inventario WHERE Precio BETWEEN "+primerValor.getValue()+" AND "+segundoValor.getValue()+" ORDER BY Precio");
            else
                resultado=objConexion.consultarRegistro("SELECT * FROM Inventario WHERE Precio BETWEEN "+primerValor.getValue()+" AND "+segundoValor.getValue()+" ORDER BY Precio DESC");
            while(resultado.next()){
                Object[] objUsuario = {resultado.getString("Codigo_Barras"), resultado.getString("Nombre"), 
                    resultado.getString("Precio"), resultado.getString("Marca"), resultado.getString("Fecha_Ingreso"), 
                    resultado.getString("Stock"), resultado.getString("Tipo"), resultado.getString("Ventas_Dia"), resultado.getString("Ventas_Mes")};
                modelo.addRow(objUsuario);
            }
        }catch(Exception e){
            System.out.println("Error de consulta "+e);
        }
        objConexion.close();
    }//GEN-LAST:event_costosBotonActionPerformed

    private void ordenarPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarPorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ordenarPorActionPerformed

    private void consultaGeneralBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaGeneralBotonActionPerformed
        // TODO add your handling code here:
        while(modelo.getRowCount()>0)
            modelo.removeRow(0);
        Conexion objConexion=new Conexion();
        try{
            ResultSet resultado=objConexion.consultarRegistro("SELECT * FROM Inventario");
            while(resultado.next()){
                Object[] objUsuario = {resultado.getString("Codigo_Barras"), resultado.getString("Nombre"), 
                    resultado.getString("Precio"), resultado.getString("Marca"), resultado.getString("Fecha_Ingreso"), 
                    resultado.getString("Stock"), resultado.getString("Tipo"), resultado.getString("Ventas_Dia"), 
                    resultado.getString("Ventas_Mes")};
                modelo.addRow(objUsuario);
            }
        }catch(Exception e){
            System.out.println("Error de consulta "+e);
        }
        objConexion.close();
    }//GEN-LAST:event_consultaGeneralBotonActionPerformed

    private void RegresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_RegresarButtonActionPerformed

    private void AyudaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyudaButtonActionPerformed
        // TODO add your handling code here:
        //textblock
        JOptionPane.showMessageDialog(null, """
            Para consultar un dato se debe escribir el campo por el que se va a
            consultar, después se debe pulsar su botón "Consultar". Si se quiere
            consultar por ventas del dia, ventas vensuales o sin un campo en
            específico, se debe pulsar en los botones anteriormente mencionados""", "Ayuda", JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_AyudaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AyudaButton;
    private javax.swing.JButton RegresarButton;
    private javax.swing.JButton codigoBoton;
    private javax.swing.JPanel codigoPanel;
    private javax.swing.JTextField codigo_Field;
    private javax.swing.JButton consultaGeneralBoton;
    private javax.swing.JPanel costoPanel;
    private javax.swing.JButton costosBoton;
    private javax.swing.JSpinner diaSpinner;
    private javax.swing.JButton fechaBoton;
    private javax.swing.JPanel fechaPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner mesSpinner;
    private javax.swing.JComboBox<String> ordenarPor;
    private javax.swing.JSpinner primerValor;
    private javax.swing.JSpinner segundoValor;
    private javax.swing.JTable tablaConsultas;
    private javax.swing.JButton tipoBoton;
    private javax.swing.JComboBox<String> tipoBox;
    private javax.swing.JPanel tipoPanel;
    private javax.swing.JButton ventasDiaBoton;
    private javax.swing.JButton ventasMesBoton;
    private javax.swing.JSpinner yearSpinner;
    // End of variables declaration//GEN-END:variables
}
