/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventario;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import setConection.Conexion;
import set_get_data.Data_information;

/**
 *
 * @author easyb
 */
public class Editar extends javax.swing.JFrame {

    DefaultTableModel modelo;
    Data_information objInventario = new Data_information();
    String auxCodBarras;
    int codigoBarras;
    /**
     * Creates new form Editar
     */
    public Editar() {
        initComponents();
        this.setLocationRelativeTo(null);
        String[] titulos={"Codigo de Barras","Nombre","Precio","Marca","Fecha de Ingreso","Stock","Tipo","Ventas del dia","Ventas del mes","Descuentos"};
        modelo = new DefaultTableModel(null, titulos);
        tablaInventario.setModel(modelo);
        mostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        aceptarBoton = new javax.swing.JButton();
        RegresarButton = new javax.swing.JButton();
        ActualizarButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        fecha_Field = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        codigo_Field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        stock_Field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ventasMes_Field = new javax.swing.JTextField();
        descuento_Box = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        marca_Field = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ventasDia_Field = new javax.swing.JTextField();
        nombre_Field = new javax.swing.JTextField();
        precio_Field = new javax.swing.JTextField();
        tipoBox = new javax.swing.JComboBox<>();
        AyudaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(110, 140, 100));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 0));
        jLabel2.setText("EDITAR");

        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo de Barras", "Nombre", "Precio", "Marca", "Fecha ", "Stock", "Tipo", "Ventas Dia", "Ventas Mes", "Descuento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaInventario.getTableHeader().setReorderingAllowed(false);
        tablaInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaInventarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaInventario);

        aceptarBoton.setBackground(new java.awt.Color(0, 205, 20));
        aceptarBoton.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        aceptarBoton.setForeground(new java.awt.Color(0, 55, 0));
        aceptarBoton.setText("ACEPTAR");
        aceptarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBotonActionPerformed(evt);
            }
        });

        RegresarButton.setBackground(new java.awt.Color(90, 0, 0));
        RegresarButton.setFont(new java.awt.Font("Segoe UI Symbol", 0, 28)); // NOI18N
        RegresarButton.setForeground(new java.awt.Color(200, 0, 0));
        RegresarButton.setText("↩");
        RegresarButton.setToolTipText("Regresar");
        RegresarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarButtonActionPerformed(evt);
            }
        });

        ActualizarButton.setBackground(new java.awt.Color(50, 50, 0));
        ActualizarButton.setFont(new java.awt.Font("Segoe UI Symbol", 0, 30)); // NOI18N
        ActualizarButton.setForeground(new java.awt.Color(150, 200, 0));
        ActualizarButton.setText("↻");
        ActualizarButton.setToolTipText("Actualizar");
        ActualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarButtonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(100, 110, 130));

        jLabel7.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 51));
        jLabel7.setText("Tipo:");

        fecha_Field.setEditable(false);
        fecha_Field.setBackground(new java.awt.Color(70, 75, 100));
        fecha_Field.setForeground(new java.awt.Color(187, 197, 187));
        fecha_Field.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(20, 50, 100))); // NOI18N
        fecha_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecha_FieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 51));
        jLabel9.setText("Ventas dia:");

        codigo_Field.setEditable(false);
        codigo_Field.setBackground(new java.awt.Color(70, 75, 100));
        codigo_Field.setForeground(new java.awt.Color(187, 197, 187));
        codigo_Field.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(20, 50, 100))); // NOI18N
        codigo_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigo_FieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 51));
        jLabel3.setText("Nombre:");

        jLabel11.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 255, 51));
        jLabel11.setText("Descuento:");

        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 51));
        jLabel6.setText("Fecha:");

        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 51));
        jLabel4.setText("Precio:");

        stock_Field.setBackground(new java.awt.Color(70, 75, 100));
        stock_Field.setForeground(new java.awt.Color(187, 197, 187));
        stock_Field.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(20, 50, 100))); // NOI18N
        stock_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stock_FieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("Codigo de Barras:");

        ventasMes_Field.setBackground(new java.awt.Color(70, 75, 100));
        ventasMes_Field.setForeground(new java.awt.Color(187, 197, 187));
        ventasMes_Field.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(20, 50, 100))); // NOI18N
        ventasMes_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasMes_FieldActionPerformed(evt);
            }
        });

        descuento_Box.setBackground(new java.awt.Color(70, 75, 100));
        descuento_Box.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        descuento_Box.setForeground(new java.awt.Color(187, 197, 187));
        descuento_Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "10", "20", "50" }));
        descuento_Box.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(20, 50, 100))); // NOI18N
        descuento_Box.setOpaque(true);

        jLabel10.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 51));
        jLabel10.setText("Ventas mes:");

        jLabel5.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 51));
        jLabel5.setText("Marca:");

        marca_Field.setBackground(new java.awt.Color(70, 75, 100));
        marca_Field.setForeground(new java.awt.Color(187, 197, 187));
        marca_Field.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(20, 50, 100))); // NOI18N
        marca_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marca_FieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 51));
        jLabel8.setText("Stock:");

        ventasDia_Field.setBackground(new java.awt.Color(70, 75, 100));
        ventasDia_Field.setForeground(new java.awt.Color(187, 197, 187));
        ventasDia_Field.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(20, 50, 100))); // NOI18N
        ventasDia_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasDia_FieldActionPerformed(evt);
            }
        });

        nombre_Field.setBackground(new java.awt.Color(70, 75, 100));
        nombre_Field.setForeground(new java.awt.Color(187, 197, 187));
        nombre_Field.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(20, 50, 100))); // NOI18N
        nombre_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_FieldActionPerformed(evt);
            }
        });

        precio_Field.setBackground(new java.awt.Color(70, 75, 100));
        precio_Field.setForeground(new java.awt.Color(187, 197, 187));
        precio_Field.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(20, 50, 100))); // NOI18N
        precio_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precio_FieldActionPerformed(evt);
            }
        });

        tipoBox.setBackground(new java.awt.Color(70, 75, 100));
        tipoBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tipoBox.setForeground(new java.awt.Color(187, 197, 187));
        tipoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electrodomésticos", "Comida", "Hogar", "Herramienta", "Vestimenta", "Higiene", "Farmacia", "Otros" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nombre_Field))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(fecha_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(marca_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(precio_Field)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(codigo_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ventasDia_Field)
                            .addComponent(tipoBox, 0, 340, Short.MAX_VALUE)
                            .addComponent(stock_Field)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descuento_Box, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ventasMes_Field))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(codigo_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nombre_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(precio_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(marca_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fecha_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stock_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(tipoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(ventasDia_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(ventasMes_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descuento_Box, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        AyudaButton.setBackground(new java.awt.Color(102, 102, 0));
        AyudaButton.setFont(new java.awt.Font("Segoe UI Symbol", 0, 30)); // NOI18N
        AyudaButton.setForeground(new java.awt.Color(255, 255, 0));
        AyudaButton.setText("?");
        AyudaButton.setToolTipText("Ayuda");
        AyudaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AyudaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(433, 433, 433)
                        .addComponent(aceptarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 466, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(RegresarButton)
                .addGap(424, 424, 424)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AyudaButton)
                .addGap(18, 18, 18)
                .addComponent(ActualizarButton)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(RegresarButton)
                    .addComponent(ActualizarButton)
                    .addComponent(AyudaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(aceptarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fecha_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecha_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha_FieldActionPerformed

    private void precio_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precio_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precio_FieldActionPerformed

    private void marca_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marca_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marca_FieldActionPerformed

    private void codigo_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigo_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigo_FieldActionPerformed

    private void nombre_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_FieldActionPerformed

    private void aceptarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBotonActionPerformed
        // TODO add your handling code here:
        int opcion = JOptionPane.showConfirmDialog(null,"¿Deseas Confirmar?","Editar",JOptionPane.OK_CANCEL_OPTION);
        if(opcion == JOptionPane.OK_OPTION){
            String errMessage="";
            //sacar el codigo de barras
            if(codigo_Field.getText().isEmpty() || !codigo_Field.getText().trim().matches("\\d{1,9}"))
                errMessage += " 'Codigo de barras' ";
            //sacar el nombre
            if(nombre_Field.getText().isEmpty() || !nombre_Field.getText().trim().matches("[\\w\\s]{1,100}"))
                errMessage += " 'Nombre' ";
            //sacar el precio
            if(precio_Field.getText().isEmpty() || !precio_Field.getText().trim().matches("\\d+(\\.\\d{1,2})?"))
                errMessage += " 'Precio' ";
            //sacar la marca
            if(marca_Field.getText().isEmpty() || !marca_Field.getText().trim().matches("[\\w\\s]{1,50}"))
                errMessage += " 'Marca' ";
            //sacar la cantidad/stock
            if(stock_Field.getText().isEmpty() || !stock_Field.getText().trim().matches("\\d+"))
                errMessage += " 'Cantidad' ";
            //sacar las ventas del dia
            if(ventasDia_Field.getText().isEmpty() || !ventasDia_Field.getText().trim().matches("\\d+"))
                errMessage += " 'Ventas dia' ";
            //sacar las ventas del mes
            if(ventasMes_Field.getText().isEmpty() || !ventasMes_Field.getText().trim().matches("\\d+"))
                errMessage += " 'Ventas mes' ";
            if(!errMessage.equals("")){
                JOptionPane.showMessageDialog(null,"Los campos"+errMessage+"se encuentran vacios o son erroneos","Error",JOptionPane.ERROR_MESSAGE);
                //error=true;
            }else{
                Conexion objConexion = new Conexion();
                String strSentenciaInsert = String.format("UPDATE Inventario SET Codigo_Barras=%s,Nombre='%s',Precio=%s,"
                        + "Marca='%s',Fecha_Ingreso='%s',Stock=%s,Tipo='%s',Ventas_Dia=%s,Ventas_Mes=%s,Descuento=%s WHERE Codigo_Barras=%d",codigo_Field.getText(),nombre_Field.getText(),
                        precio_Field.getText(),marca_Field.getText(),fecha_Field.getText(),stock_Field.getText(),tipoBox.getSelectedItem(),
                        ventasDia_Field.getText(),ventasMes_Field.getText(),descuento_Box.getSelectedItem(),codigoBarras);
                if(objConexion.ejecutarSentenciaSQL(strSentenciaInsert) == 1)
                    JOptionPane.showMessageDialog(null, "Modificación realizada con éxito", "Ventas", JOptionPane.INFORMATION_MESSAGE);
                else
                    JOptionPane.showMessageDialog(null, "Error al realizar la modificación", "Ventas", JOptionPane.ERROR_MESSAGE); 
                objConexion.close();
            }
        }
        mostrarDatos();
    }//GEN-LAST:event_aceptarBotonActionPerformed

    private void tablaInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaInventarioMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==1){
            JTable receptor = (JTable)evt.getSource();
            codigo_Field.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString());
            auxCodBarras = receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString();
            codigoBarras = Integer.parseInt(auxCodBarras);
            nombre_Field.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 1).toString());
            precio_Field.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 2).toString());
            marca_Field.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 3).toString());
            fecha_Field.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 4).toString());
            stock_Field.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 5).toString());
            tipoBox.setSelectedItem(receptor.getModel().getValueAt(receptor.getSelectedRow(), 6).toString());
            ventasDia_Field.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 7).toString());
            ventasMes_Field.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 8).toString());
            descuento_Box.setSelectedItem(receptor.getModel().getValueAt(receptor.getSelectedRow(), 9).toString());
            
            /*auxCodBarras = receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString();
            objInventario.setCodigo_barras(Long.parseLong(auxCodBarras));
            objInventario.setNombre(receptor.getModel().getValueAt(receptor.getSelectedRow(), 1).toString());
            auxPrecio = receptor.getModel().getValueAt(receptor.getSelectedRow(), 2).toString();
            objInventario.setPrecio(Double.parseDouble(auxPrecio));
            objInventario.setMarca(receptor.getModel().getValueAt(receptor.getSelectedRow(), 3).toString());
            objInventario.setFecha(receptor.getModel().getValueAt(receptor.getSelectedRow(), 4).toString());
            auxStock = receptor.getModel().getValueAt(receptor.getSelectedRow(), 5).toString();
            objInventario.setStock(Integer.parseInt(auxStock));
            objInventario.setTipo(receptor.getModel().getValueAt(receptor.getSelectedRow(), 6).toString());
            auxVentasDia = receptor.getModel().getValueAt(receptor.getSelectedRow(), 7).toString();
            objInventario.setVentasDia(Integer.parseInt(auxVentasDia));
            auxVentasMes = receptor.getModel().getValueAt(receptor.getSelectedRow(), 8).toString();
            objInventario.setVentasMes(Integer.parseInt(auxVentasMes));*/
        }
    }//GEN-LAST:event_tablaInventarioMouseClicked

    private void stock_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stock_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stock_FieldActionPerformed

    private void ventasDia_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasDia_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ventasDia_FieldActionPerformed

    private void ventasMes_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasMes_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ventasMes_FieldActionPerformed

    private void RegresarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_RegresarButtonActionPerformed

    private void ActualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarButtonActionPerformed
        // TODO add your handling code here:
        mostrarDatos();
    }//GEN-LAST:event_ActualizarButtonActionPerformed

    private void AyudaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AyudaButtonActionPerformed
        // TODO add your handling code here:
        //textblock
        JOptionPane.showMessageDialog(null, """
            Para modificar un dato se debe seleccionar la fila o el dato a modificar, 
            después se hacen los cambios correspondientes en los campos de texto 
            para finalmente pulsar el botón aceptar""", "Ayuda", JOptionPane.QUESTION_MESSAGE);
    }//GEN-LAST:event_AyudaButtonActionPerformed

    public void mostrarDatos(){
        //limpiar la tabla cada que se hace una llamada a mostrar datos
        while(modelo.getRowCount()>0)
            modelo.removeRow(0);
        Conexion objConexion=new Conexion();
        try{
            ResultSet resultado=objConexion.consultarRegistro("SELECT * FROM Inventario");
            while(resultado.next()){
                Object[] objUsuario = {resultado.getString("Codigo_Barras"), resultado.getString("Nombre"), 
                    resultado.getString("Precio"), resultado.getString("Marca"), resultado.getString("Fecha_Ingreso"), 
                    resultado.getString("Stock"), resultado.getString("Tipo"), resultado.getString("Ventas_Dia"),
                    resultado.getString("Ventas_Mes"), resultado.getString("Descuento")};
                modelo.addRow(objUsuario);
            }
        }catch(Exception e){
            System.out.println("Error de consulta "+e);
        }
        objConexion.close();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarButton;
    private javax.swing.JButton AyudaButton;
    private javax.swing.JButton RegresarButton;
    private javax.swing.JButton aceptarBoton;
    private javax.swing.JTextField codigo_Field;
    private javax.swing.JComboBox<String> descuento_Box;
    private javax.swing.JTextField fecha_Field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField marca_Field;
    private javax.swing.JTextField nombre_Field;
    private javax.swing.JTextField precio_Field;
    private javax.swing.JTextField stock_Field;
    private javax.swing.JTable tablaInventario;
    private javax.swing.JComboBox<String> tipoBox;
    private javax.swing.JTextField ventasDia_Field;
    private javax.swing.JTextField ventasMes_Field;
    // End of variables declaration//GEN-END:variables
}
