/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventario;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import setConection.Conexion;


/**
 *
 * @author easyb
 */
public class Menu extends javax.swing.JFrame {
    
    JFrame ventana = null;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Agregar1 = new javax.swing.JButton();
        Venta = new javax.swing.JButton();
        Baja = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Consultar = new javax.swing.JButton();
        Archivos = new javax.swing.JButton();
        CorteCaja = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor de Invetarios");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(20, 70, 65));
        jPanel1.setMaximumSize(new java.awt.Dimension(986, 569));
        jPanel1.setMinimumSize(new java.awt.Dimension(986, 569));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 56)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(50, 190, 30));
        jLabel1.setText("O.X.X.O");

        jPanel3.setBackground(new java.awt.Color(110, 140, 100));

        Agregar1.setBackground(new java.awt.Color(30, 45, 38));
        Agregar1.setFont(new java.awt.Font("Agency FB", 0, 48)); // NOI18N
        Agregar1.setForeground(new java.awt.Color(50, 190, 70));
        Agregar1.setText("AGREGAR");
        Agregar1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 205, 51))); // NOI18N
        Agregar1.setOpaque(true);
        Agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar1ActionPerformed(evt);
            }
        });

        Venta.setBackground(new java.awt.Color(30, 45, 38));
        Venta.setFont(new java.awt.Font("Agency FB", 0, 48)); // NOI18N
        Venta.setForeground(new java.awt.Color(50, 190, 70));
        Venta.setText("VENTAS");
        Venta.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 205, 51))); // NOI18N
        Venta.setOpaque(true);
        Venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentaActionPerformed(evt);
            }
        });

        Baja.setBackground(new java.awt.Color(30, 45, 38));
        Baja.setFont(new java.awt.Font("Agency FB", 0, 48)); // NOI18N
        Baja.setForeground(new java.awt.Color(50, 190, 70));
        Baja.setText("BAJA");
        Baja.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 205, 51))); // NOI18N
        Baja.setOpaque(true);
        Baja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajaActionPerformed(evt);
            }
        });

        Modificar.setBackground(new java.awt.Color(30, 45, 38));
        Modificar.setFont(new java.awt.Font("Agency FB", 0, 48)); // NOI18N
        Modificar.setForeground(new java.awt.Color(50, 190, 70));
        Modificar.setText("MODIFICAR");
        Modificar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 205, 51))); // NOI18N
        Modificar.setOpaque(true);
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        Consultar.setBackground(new java.awt.Color(30, 45, 38));
        Consultar.setFont(new java.awt.Font("Agency FB", 0, 48)); // NOI18N
        Consultar.setForeground(new java.awt.Color(50, 190, 70));
        Consultar.setText("CONSULTAR");
        Consultar.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 205, 51))); // NOI18N
        Consultar.setOpaque(true);
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });

        Archivos.setBackground(new java.awt.Color(30, 45, 38));
        Archivos.setFont(new java.awt.Font("Agency FB", 0, 48)); // NOI18N
        Archivos.setForeground(new java.awt.Color(50, 190, 70));
        Archivos.setText("ARCHIVOS");
        Archivos.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 205, 51))); // NOI18N
        Archivos.setOpaque(true);
        Archivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArchivosActionPerformed(evt);
            }
        });

        CorteCaja.setBackground(new java.awt.Color(30, 45, 38));
        CorteCaja.setFont(new java.awt.Font("Agency FB", 0, 48)); // NOI18N
        CorteCaja.setForeground(new java.awt.Color(50, 190, 70));
        CorteCaja.setText("CORTE DE CAJA");
        CorteCaja.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 205, 51))); // NOI18N
        CorteCaja.setOpaque(true);
        CorteCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorteCajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Agregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(Venta, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(Baja, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CorteCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(Archivos, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Agregar1)
                    .addComponent(Venta)
                    .addComponent(Baja))
                .addGap(106, 106, 106)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Modificar)
                    .addComponent(Consultar)
                    .addComponent(Archivos))
                .addGap(106, 106, 106)
                .addComponent(CorteCaja))
        );

        salirButton.setBackground(new java.awt.Color(90, 0, 0));
        salirButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        salirButton.setForeground(new java.awt.Color(187, 189, 187));
        salirButton.setText("Salir");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(438, 438, 438)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar1ActionPerformed
        // TODO add your handling code here:
        //CREACION DE JFRAME INTERNO
        if(ventana == null || !ventana.isVisible()){
            ventana = new RegistroF();
            ventana.setVisible(true);
        }else
            JOptionPane.showMessageDialog(null, "Hay una ventana activa", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_Agregar1ActionPerformed

    private void ArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArchivosActionPerformed
        // TODO add your handling code here:
        if(ventana == null || !ventana.isVisible()){
            ventana = new Archivos();
            ventana.setVisible(true);
        }else
            JOptionPane.showMessageDialog(null, "Hay una ventana activa", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_ArchivosActionPerformed

    private void CorteCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorteCajaActionPerformed
        // TODO add your handling code here:
        double ventasTot=0,precioProd,aux=0;
        int ventaProd,descuentoProd,ventaMensual;
        
        if(ventana == null || !ventana.isVisible()){
            int opcion = JOptionPane.showConfirmDialog(null,"¿Deseas Confirmar?","Editar",JOptionPane.OK_CANCEL_OPTION);
            if(opcion == JOptionPane.OK_OPTION){
                try {
                    Conexion objConexion = new Conexion();
                    String strSentenciaInsert = String.format("SELECT * FROM Inventario WHERE Ventas_Dia>0");
                    objConexion.ejecutarSentenciaSQL(strSentenciaInsert);

                    ResultSet resultado=objConexion.consultarRegistro("SELECT * FROM Inventario WHERE Ventas_Dia>0");
                    
                    while(resultado.next()){    //se obtiene la cantidad total de ingresos tras las ventas del dia
                        
                        ventaProd = Integer.parseInt(resultado.getString("Ventas_Dia"));
                        precioProd = Double.parseDouble(resultado.getString("Precio"));
                        descuentoProd = Integer.parseInt(resultado.getString("Descuento"));
                        ventaMensual = Integer.parseInt(resultado.getString("Ventas_Mes"));
                        
                        strSentenciaInsert = String.format("UPDATE Inventario SET Ventas_Dia=0, Ventas_Mes=%d WHERE Codigo_Barras=%s",ventaProd+ventaMensual,resultado.getString("Codigo_Barras"));
                        objConexion.ejecutarSentenciaSQL(strSentenciaInsert);
                        
                        aux = (100 - descuentoProd);
                        ventasTot += ventaProd * precioProd * aux / 100;
                        
                    }
                    
                    JOptionPane.showMessageDialog(null, "Ventas totales: $" + ventasTot, "Ganancias", JOptionPane.INFORMATION_MESSAGE);
                    
                    objConexion.close();
                } catch (Exception e) {
                    System.out.println("Error en la cosulta de la base de datos "+e);
                }

            }
        }else
            JOptionPane.showMessageDialog(null, "Hay una ventana activa", "Error", JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_CorteCajaActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        // TODO add your handling code here:
        if(ventana == null || !ventana.isVisible()){
            ventana = new Consultas();
            ventana.setVisible(true);
        }else
            JOptionPane.showMessageDialog(null, "Hay una ventana activa", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_ConsultarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
        if(ventana == null || !ventana.isVisible()){
            ventana = new Editar();
            ventana.setVisible(true);
        }else
            JOptionPane.showMessageDialog(null, "Hay una ventana activa", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_ModificarActionPerformed

    private void VentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentaActionPerformed
        // TODO add your handling code here:
        if(ventana == null || !ventana.isVisible()){
            ventana = new Baja();
            ventana.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Hay una ventana activa", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_VentaActionPerformed

    private void BajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajaActionPerformed
        // TODO add your handling code here:
        if(ventana == null || !ventana.isVisible()){
            ventana = new Eliminar();
            ventana.setVisible(true);
        }else
            JOptionPane.showMessageDialog(null, "Hay una ventana activa", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_BajaActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_salirButtonActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar1;
    private javax.swing.JButton Archivos;
    private javax.swing.JButton Baja;
    private javax.swing.JButton Consultar;
    private javax.swing.JButton CorteCaja;
    private javax.swing.JButton Modificar;
    private javax.swing.JButton Venta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton salirButton;
    // End of variables declaration//GEN-END:variables
}
