/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gatoGrafico;

import java.awt.Color;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;


/**
 *
 * @author josel
 */
public class GatoGrafico extends javax.swing.JFrame implements Runnable {

    String ampm,hora,minuto,segundo;
    Calendar calendario;
    Thread hilo;
    boolean turno=true; //true = X   false = O
    int puntosX=0;
    int puntosO=0;
    boolean gano=false;
    /**
     * Creates new form GatoGrafico
     */
    public GatoGrafico() {
        initComponents();
        hilo = new Thread(this);
        hilo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        TicTacToe = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        ScoreBoard = new javax.swing.JPanel();
        Score = new javax.swing.JLabel();
        Jugador_X = new javax.swing.JLabel();
        Jugador_O = new javax.swing.JLabel();
        Puntuacion_X = new javax.swing.JLabel();
        Puntuacion_O = new javax.swing.JLabel();
        lbReloj = new javax.swing.JLabel();
        NuevoJuego = new javax.swing.JButton();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(187, 187, 187));
        jPanel2.setForeground(new java.awt.Color(60, 63, 65));

        TicTacToe.setLayout(new java.awt.GridLayout(3, 3));

        jButton1.setBackground(new java.awt.Color(187, 187, 187));
        jButton1.setFont(new java.awt.Font("Corbel", 1, 45)); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        TicTacToe.add(jButton1);

        jButton2.setBackground(new java.awt.Color(187, 187, 187));
        jButton2.setFont(new java.awt.Font("Corbel", 1, 45)); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        TicTacToe.add(jButton2);

        jButton3.setBackground(new java.awt.Color(187, 187, 187));
        jButton3.setFont(new java.awt.Font("Corbel", 1, 45)); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        TicTacToe.add(jButton3);

        jButton4.setBackground(new java.awt.Color(187, 187, 187));
        jButton4.setFont(new java.awt.Font("Corbel", 1, 45)); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        TicTacToe.add(jButton4);

        jButton5.setBackground(new java.awt.Color(187, 187, 187));
        jButton5.setFont(new java.awt.Font("Corbel", 1, 45)); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        TicTacToe.add(jButton5);

        jButton6.setBackground(new java.awt.Color(187, 187, 187));
        jButton6.setFont(new java.awt.Font("Corbel", 1, 45)); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        TicTacToe.add(jButton6);

        jButton7.setBackground(new java.awt.Color(187, 187, 187));
        jButton7.setFont(new java.awt.Font("Corbel", 1, 45)); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        TicTacToe.add(jButton7);

        jButton8.setBackground(new java.awt.Color(187, 187, 187));
        jButton8.setFont(new java.awt.Font("Corbel", 1, 45)); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        TicTacToe.add(jButton8);

        jButton9.setBackground(new java.awt.Color(187, 187, 187));
        jButton9.setFont(new java.awt.Font("Corbel", 1, 45)); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        TicTacToe.add(jButton9);

        ScoreBoard.setBackground(new java.awt.Color(107, 150, 107));
        ScoreBoard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Score.setFont(new java.awt.Font("Cooper Black", 1, 30)); // NOI18N
        Score.setForeground(new java.awt.Color(200, 230, 200));
        Score.setText("SCORE");

        Jugador_X.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        Jugador_X.setForeground(new java.awt.Color(207, 207, 208));
        Jugador_X.setText("Jugador X: ");

        Jugador_O.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        Jugador_O.setForeground(new java.awt.Color(207, 207, 208));
        Jugador_O.setText("Jugador O: ");

        Puntuacion_X.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        Puntuacion_X.setForeground(new java.awt.Color(207, 207, 208));
        Puntuacion_X.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Puntuacion_X.setText("0");
        Puntuacion_X.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        Puntuacion_O.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        Puntuacion_O.setForeground(new java.awt.Color(207, 207, 208));
        Puntuacion_O.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Puntuacion_O.setText("0");
        Puntuacion_O.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbReloj.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        lbReloj.setForeground(new java.awt.Color(207, 207, 208));
        lbReloj.setText("00:00:00:AM");

        javax.swing.GroupLayout ScoreBoardLayout = new javax.swing.GroupLayout(ScoreBoard);
        ScoreBoard.setLayout(ScoreBoardLayout);
        ScoreBoardLayout.setHorizontalGroup(
            ScoreBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScoreBoardLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(Score)
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(ScoreBoardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ScoreBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ScoreBoardLayout.createSequentialGroup()
                        .addComponent(Jugador_X)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Puntuacion_X, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ScoreBoardLayout.createSequentialGroup()
                        .addComponent(Jugador_O)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Puntuacion_O, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ScoreBoardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbReloj)
                .addGap(66, 66, 66))
        );
        ScoreBoardLayout.setVerticalGroup(
            ScoreBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScoreBoardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Score)
                .addGap(42, 42, 42)
                .addGroup(ScoreBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jugador_X)
                    .addComponent(Puntuacion_X))
                .addGap(47, 47, 47)
                .addGroup(ScoreBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jugador_O)
                    .addComponent(Puntuacion_O))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(lbReloj)
                .addGap(15, 15, 15))
        );

        NuevoJuego.setBackground(new java.awt.Color(38, 50, 82));
        NuevoJuego.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NuevoJuego.setForeground(new java.awt.Color(187, 187, 188));
        NuevoJuego.setText("NUEVO JUEGO");
        NuevoJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoJuegoActionPerformed(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(98, 30, 42));
        Salir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Salir.setForeground(new java.awt.Color(187, 187, 188));
        Salir.setText("SALIR");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TicTacToe, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NuevoJuego, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ScoreBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TicTacToe, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ScoreBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NuevoJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setScore()
    {
        Puntuacion_X.setText(Integer.toString(puntosX));
        Puntuacion_O.setText(Integer.toString(puntosO));
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!gano)
        {
            if (turno) {
                jButton1.setText("X");
                jButton1.setForeground(Color.red);
                turno = false;
            }else{
                jButton1.setText("O");
                jButton1.setForeground(Color.blue);
                turno = true;
            }
            jButton1.setEnabled(false);
            ganador();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(!gano)
        {
            if (turno) {
                jButton2.setText("X");
                jButton2.setForeground(Color.red);
                turno = false;
            }else{
                jButton2.setText("O");
                jButton2.setForeground(Color.blue);
                turno = true;
            }
            jButton2.setEnabled(false);
            ganador();
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(!gano)
        {
            if (turno) {
                jButton3.setText("X");
                jButton3.setForeground(Color.red);
                turno = false;
            }else{
                jButton3.setText("O");
                jButton3.setForeground(Color.blue);
                turno = true;
            }
            jButton3.setEnabled(false);
            ganador();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(!gano)
        {
            if (turno) {
                jButton4.setText("X");
                jButton4.setForeground(Color.red);
                turno = false;
            }else{
                jButton4.setText("O");
                jButton4.setForeground(Color.blue);
                turno = true;
            }
            jButton4.setEnabled(false);
            ganador();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(!gano)
        {
            if (turno) {
                jButton5.setText("X");
                jButton5.setForeground(Color.red);
                turno = false;
            }else{
                jButton5.setText("O");
                jButton5.setForeground(Color.blue);
                turno = true;
            }
            jButton5.setEnabled(false);
            ganador();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(!gano)
        {
            if (turno) {
                jButton6.setText("X");
                jButton6.setForeground(Color.red);
                turno = false;
            }else{
                jButton6.setText("O");
                jButton6.setForeground(Color.blue);
                turno = true;
            }
            jButton6.setEnabled(false);
            ganador();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(!gano)
        {
            if (turno) {
                jButton7.setText("X");
                jButton7.setForeground(Color.red);
                turno = false;
            }else{
                jButton7.setText("O");
                jButton7.setForeground(Color.blue);
                turno = true;
            }
            jButton7.setEnabled(false);
            ganador();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(!gano)
        {
            if (turno) {
                jButton8.setText("X");
                jButton8.setForeground(Color.red);
                turno = false;
            }else{
                jButton8.setText("O");
                jButton8.setForeground(Color.blue);
                turno = true;
            }
            jButton8.setEnabled(false);
            ganador();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if(!gano)
        {
            if (turno) {
                jButton9.setText("X");
                jButton9.setForeground(Color.red);
                turno = false;
            }else{
                jButton9.setText("O");
                jButton9.setForeground(Color.blue);
                turno = true;
            }
            jButton9.setEnabled(false);
            ganador();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void NuevoJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoJuegoActionPerformed
        // TODO add your handling code here:
        jButton1.setText("");
        jButton1.setEnabled(true);
        jButton2.setText("");
        jButton2.setEnabled(true);
        jButton3.setText("");
        jButton3.setEnabled(true);
        jButton4.setText("");
        jButton4.setEnabled(true);
        jButton5.setText("");
        jButton5.setEnabled(true);
        jButton6.setText("");
        jButton6.setEnabled(true);
        jButton7.setText("");
        jButton7.setEnabled(true);
        jButton8.setText("");
        jButton8.setEnabled(true);
        jButton9.setText("");
        jButton9.setEnabled(true);
        
        jButton1.setBackground(Color.lightGray);
        jButton2.setBackground(Color.lightGray);
        jButton3.setBackground(Color.lightGray);
        jButton4.setBackground(Color.lightGray);
        jButton5.setBackground(Color.lightGray);
        jButton6.setBackground(Color.lightGray);
        jButton7.setBackground(Color.lightGray);
        jButton8.setBackground(Color.lightGray);
        jButton9.setBackground(Color.lightGray);
        
        gano=false;
    }//GEN-LAST:event_NuevoJuegoActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void ganador()
    {
        String b1 = jButton1.getText();
        String b2 = jButton2.getText();
        String b3 = jButton3.getText();
        String b4 = jButton4.getText();
        String b5 = jButton5.getText();
        String b6 = jButton6.getText();
        String b7 = jButton7.getText();
        String b8 = jButton8.getText();
        String b9 = jButton9.getText();
        
        //jugador X
        if(b1 == "X" && b2 == "X" && b3 == "X")
        {
            puntosX++;
            setScore();
            jButton1.setBackground(Color.RED);
            jButton2.setBackground(Color.RED);
            jButton3.setBackground(Color.RED);
            jButton1.setForeground(Color.lightGray);
            jButton2.setForeground(Color.lightGray);
            jButton3.setForeground(Color.lightGray);
            gano=true;
        }
       
        if(b4 == "X" && b5 == "X" && b6 == "X")
        {
            puntosX++;
            setScore();
            jButton4.setBackground(Color.RED);
            jButton5.setBackground(Color.RED);
            jButton6.setBackground(Color.RED);
            jButton4.setForeground(Color.lightGray);
            jButton5.setForeground(Color.lightGray);
            jButton6.setForeground(Color.lightGray);
            gano=true;
        }
        
        if(b7 == "X" && b8 == "X" && b9 == "X")
        {
            puntosX++;
            setScore();
            jButton7.setBackground(Color.RED);
            jButton8.setBackground(Color.RED);
            jButton9.setBackground(Color.RED);
            jButton7.setForeground(Color.lightGray);
            jButton8.setForeground(Color.lightGray);
            jButton9.setForeground(Color.lightGray);
            gano=true;
        }
        
        if(b1 == "X" && b4 == "X" && b7 == "X")
        {
            puntosX++;
            setScore();
            jButton1.setBackground(Color.RED);
            jButton4.setBackground(Color.RED);
            jButton7.setBackground(Color.RED);
            jButton1.setForeground(Color.lightGray);
            jButton4.setForeground(Color.lightGray);
            jButton7.setForeground(Color.lightGray);
            gano=true;
        }
       
        if(b2 == "X" && b5 == "X" && b8 == "X")
        {
            puntosX++;
            setScore();
            jButton2.setBackground(Color.RED);
            jButton5.setBackground(Color.RED);
            jButton8.setBackground(Color.RED);
            jButton2.setForeground(Color.lightGray);
            jButton5.setForeground(Color.lightGray);
            jButton8.setForeground(Color.lightGray);
            gano=true;
        }
        
        if(b3 == "X" && b6 == "X" && b9 == "X")
        {
            puntosX++;
            setScore();
            jButton3.setBackground(Color.RED);
            jButton6.setBackground(Color.RED);
            jButton9.setBackground(Color.RED);
            jButton3.setForeground(Color.lightGray);
            jButton6.setForeground(Color.lightGray);
            jButton9.setForeground(Color.lightGray);
            gano=true;
        }
        
        if(b1 == "X" && b5 == "X" && b9 == "X")
        {
            puntosX++;
            setScore();
            jButton1.setBackground(Color.RED);
            jButton5.setBackground(Color.RED);
            jButton9.setBackground(Color.RED);
            jButton1.setForeground(Color.lightGray);
            jButton5.setForeground(Color.lightGray);
            jButton9.setForeground(Color.lightGray);
            gano=true;
        }
        
        if(b3 == "X" && b5 == "X" && b7 == "X")
        {
            puntosX++;
            setScore();
            jButton3.setBackground(Color.RED);
            jButton5.setBackground(Color.RED);
            jButton7.setBackground(Color.RED);
            jButton3.setForeground(Color.lightGray);
            jButton5.setForeground(Color.lightGray);
            jButton7.setForeground(Color.lightGray);
            gano=true;
        }
        
        //jugador O
        if(b1 == "O" && b2 == "O" && b3 == "O")
        {
            puntosO++;
            setScore();
            jButton1.setBackground(Color.BLUE);
            jButton2.setBackground(Color.BLUE);
            jButton3.setBackground(Color.BLUE);
            jButton1.setForeground(Color.lightGray);
            jButton2.setForeground(Color.lightGray);
            jButton3.setForeground(Color.lightGray);
            gano=true;
        }
       
        if(b4 == "O" && b5 == "O" && b6 == "O")
        {
            puntosO++;
            setScore();
            jButton4.setBackground(Color.BLUE);
            jButton5.setBackground(Color.BLUE);
            jButton6.setBackground(Color.BLUE);
            jButton4.setForeground(Color.lightGray);
            jButton5.setForeground(Color.lightGray);
            jButton6.setForeground(Color.lightGray);
            gano=true;
        }
        
        if(b7 == "O" && b8 == "O" && b9 == "O")
        {
            puntosO++;
            setScore();
            jButton7.setBackground(Color.BLUE);
            jButton8.setBackground(Color.BLUE);
            jButton9.setBackground(Color.BLUE);
            jButton7.setForeground(Color.lightGray);
            jButton8.setForeground(Color.lightGray);
            jButton9.setForeground(Color.lightGray);
            gano=true;
        }
        
        if(b1 == "O" && b4 == "O" && b7 == "O")
        {
            puntosO++;
            setScore();
            jButton1.setBackground(Color.BLUE);
            jButton4.setBackground(Color.BLUE);
            jButton7.setBackground(Color.BLUE);
            jButton1.setForeground(Color.lightGray);
            jButton4.setForeground(Color.lightGray);
            jButton7.setForeground(Color.lightGray);
            gano=true;
        }
       
        if(b2 == "O" && b5 == "O" && b8 == "O")
        {
            puntosO++;
            setScore();
            jButton2.setBackground(Color.BLUE);
            jButton5.setBackground(Color.BLUE);
            jButton8.setBackground(Color.BLUE);
            jButton2.setForeground(Color.lightGray);
            jButton5.setForeground(Color.lightGray);
            jButton8.setForeground(Color.lightGray);
            gano=true;
        }
        
        if(b3 == "O" && b6 == "O" && b9 == "O")
        {
            puntosO++;
            setScore();
            jButton3.setBackground(Color.BLUE);
            jButton6.setBackground(Color.BLUE);
            jButton9.setBackground(Color.BLUE);
            jButton3.setForeground(Color.lightGray);
            jButton6.setForeground(Color.lightGray);
            jButton9.setForeground(Color.lightGray);
            gano=true;
        }
        
        if(b1 == "O" && b5 == "O" && b9 == "O")
        {
            puntosO++;
            setScore();
            jButton1.setBackground(Color.BLUE);
            jButton5.setBackground(Color.BLUE);
            jButton9.setBackground(Color.BLUE);
            jButton1.setForeground(Color.lightGray);
            jButton5.setForeground(Color.lightGray);
            jButton9.setForeground(Color.lightGray);
            gano=true;
        }
        
        if(b3 == "O" && b5 == "O" && b7 == "O")
        {
            puntosO++;
            setScore();
            jButton3.setBackground(Color.BLUE);
            jButton5.setBackground(Color.BLUE);
            jButton7.setBackground(Color.BLUE);
            jButton3.setForeground(Color.lightGray);
            jButton5.setForeground(Color.lightGray);
            jButton7.setForeground(Color.lightGray);
            gano=true;
        }
        
        if(gano)
        {
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);
            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
            jButton5.setEnabled(true);
            jButton6.setEnabled(true);
            jButton7.setEnabled(true);
            jButton8.setEnabled(true);
            jButton9.setEnabled(true);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GatoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GatoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GatoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GatoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GatoGrafico().setVisible(true);
            }
        });
    }
    
    private void calcula() {
      calendario=new GregorianCalendar();
      Date fechaHoraActual=new Date();
      calendario.setTime(fechaHoraActual);
      ampm=calendario.get(Calendar.AM_PM)==Calendar.AM?"AM":"PM";
      if(ampm.equals("PM")){
          int h=calendario.get(Calendar.HOUR_OF_DAY)-12;
          hora=h>9?""+h:"0"+h;
      }else{
          hora=calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get
          (Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY);
      }
      minuto=calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):
              "0"+calendario.get(Calendar.MINUTE);
      segundo=calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):
              "0"+calendario.get(Calendar.SECOND);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jugador_O;
    private javax.swing.JLabel Jugador_X;
    private javax.swing.JButton NuevoJuego;
    private javax.swing.JLabel Puntuacion_O;
    private javax.swing.JLabel Puntuacion_X;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Score;
    private javax.swing.JPanel ScoreBoard;
    private javax.swing.JPanel TicTacToe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbReloj;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        Thread ct= Thread.currentThread();
        while (ct==hilo){
            calcula();
            lbReloj.setText(hora+":"+minuto+":"+segundo+":"+ampm);
            try{
                Thread.sleep(1000);//cadasegundo
            }catch(InterruptedException e){}
        }
    
    }
}
