/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ConvertidorGrados;

/**
 *
 * @author josel
 */
public class Convertidor extends javax.swing.JFrame {

    double res;
    
    /**
     * Creates new form Convertidor
     */
    public Convertidor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField_inputCels = new javax.swing.JTextField();
        jLabel_Cels = new javax.swing.JLabel();
        jLabel_Fahr = new javax.swing.JLabel();
        jButton_Convertir = new javax.swing.JButton();
        jTextField_outputFahr = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(200, 200, 200));

        jTextField_inputCels.setBackground(new java.awt.Color(187, 187, 187));
        jTextField_inputCels.setForeground(new java.awt.Color(70, 73, 75));
        jTextField_inputCels.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_inputCels.setText("0");
        jTextField_inputCels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_inputCelsActionPerformed(evt);
            }
        });

        jLabel_Cels.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_Cels.setForeground(new java.awt.Color(20, 10, 15));
        jLabel_Cels.setText("Celsius");

        jLabel_Fahr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_Fahr.setForeground(new java.awt.Color(20, 10, 15));
        jLabel_Fahr.setText("Fahrenheit");

        jButton_Convertir.setBackground(new java.awt.Color(187, 187, 187));
        jButton_Convertir.setForeground(new java.awt.Color(78, 80, 102));
        jButton_Convertir.setText("Convertir");
        jButton_Convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConvertirActionPerformed(evt);
            }
        });

        jTextField_outputFahr.setEditable(false);
        jTextField_outputFahr.setBackground(new java.awt.Color(187, 187, 187));
        jTextField_outputFahr.setForeground(new java.awt.Color(70, 73, 75));
        jTextField_outputFahr.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_outputFahr.setText("0");
        jTextField_outputFahr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_outputFahrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_inputCels, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_outputFahr))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel_Cels, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Fahr, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButton_Convertir)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_inputCels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Cels))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Fahr)
                    .addComponent(jTextField_outputFahr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jButton_Convertir)
                .addGap(45, 45, 45))
        );

        jTextField_inputCels.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_inputCelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_inputCelsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_inputCelsActionPerformed

    private void jButton_ConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConvertirActionPerformed
        // TODO add your handling code here:
        res = Double.parseDouble(jTextField_inputCels.getText());
        
        res = (res*1.8)+32;
        
        jTextField_outputFahr.setText(Double.toString(res));
        
    }//GEN-LAST:event_jButton_ConvertirActionPerformed

    private void jTextField_outputFahrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_outputFahrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_outputFahrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Convertidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Convertir;
    private javax.swing.JLabel jLabel_Cels;
    private javax.swing.JLabel jLabel_Fahr;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_inputCels;
    private javax.swing.JTextField jTextField_outputFahr;
    // End of variables declaration//GEN-END:variables
}
