/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package joseluisespinozasanchez;

import java.awt.Color;

/**
 *
 * @author josel
 */
public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    boolean turno=true; //true = X   false = O
    int mat[][] = new int[5][5];
    int puntosX = 0;
    int puntosO = 0;
    
    public Tablero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        NuevoJuego = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cuatro en Linea");

        jPanel1.setBackground(new java.awt.Color(150, 203, 155));

        jPanel2.setLayout(new java.awt.GridLayout(5, 5));

        jButton1.setBackground(new java.awt.Color(200, 220, 200));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(20, 20, 40));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setBackground(new java.awt.Color(200, 220, 200));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(20, 20, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setBackground(new java.awt.Color(200, 220, 200));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(20, 20, 40));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        jButton4.setBackground(new java.awt.Color(200, 220, 200));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton4.setForeground(new java.awt.Color(20, 20, 40));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jButton5.setBackground(new java.awt.Color(200, 220, 200));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton5.setForeground(new java.awt.Color(20, 20, 40));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);

        jButton6.setBackground(new java.awt.Color(200, 220, 200));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton6.setForeground(new java.awt.Color(20, 20, 40));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);

        jButton7.setBackground(new java.awt.Color(200, 220, 200));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton7.setForeground(new java.awt.Color(20, 20, 40));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);

        jButton8.setBackground(new java.awt.Color(200, 220, 200));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton8.setForeground(new java.awt.Color(20, 20, 40));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);

        jButton9.setBackground(new java.awt.Color(200, 220, 200));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton9.setForeground(new java.awt.Color(20, 20, 40));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);

        jButton10.setBackground(new java.awt.Color(200, 220, 200));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton10.setForeground(new java.awt.Color(20, 20, 40));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10);

        jButton11.setBackground(new java.awt.Color(200, 220, 200));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton11.setForeground(new java.awt.Color(20, 20, 40));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11);

        jButton12.setBackground(new java.awt.Color(200, 220, 200));
        jButton12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton12.setForeground(new java.awt.Color(20, 20, 40));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton12);

        jButton13.setBackground(new java.awt.Color(200, 220, 200));
        jButton13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton13.setForeground(new java.awt.Color(20, 20, 40));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton13);

        jButton14.setBackground(new java.awt.Color(200, 220, 200));
        jButton14.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton14.setForeground(new java.awt.Color(20, 20, 40));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton14);

        jButton15.setBackground(new java.awt.Color(200, 220, 200));
        jButton15.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton15.setForeground(new java.awt.Color(20, 20, 40));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton15);

        jButton16.setBackground(new java.awt.Color(200, 220, 200));
        jButton16.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton16.setForeground(new java.awt.Color(20, 20, 40));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton16);

        jButton17.setBackground(new java.awt.Color(200, 220, 200));
        jButton17.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton17.setForeground(new java.awt.Color(20, 20, 40));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton17);

        jButton18.setBackground(new java.awt.Color(200, 220, 200));
        jButton18.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton18.setForeground(new java.awt.Color(20, 20, 40));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton18);

        jButton19.setBackground(new java.awt.Color(200, 220, 200));
        jButton19.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton19.setForeground(new java.awt.Color(20, 20, 40));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton19);

        jButton20.setBackground(new java.awt.Color(200, 220, 200));
        jButton20.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton20.setForeground(new java.awt.Color(20, 20, 40));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton20);

        jButton21.setBackground(new java.awt.Color(200, 220, 200));
        jButton21.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton21.setForeground(new java.awt.Color(20, 20, 40));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton21);

        jButton22.setBackground(new java.awt.Color(200, 220, 200));
        jButton22.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton22.setForeground(new java.awt.Color(20, 20, 40));
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton22);

        jButton23.setBackground(new java.awt.Color(200, 220, 200));
        jButton23.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton23.setForeground(new java.awt.Color(20, 20, 40));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton23);

        jButton24.setBackground(new java.awt.Color(200, 220, 200));
        jButton24.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton24.setForeground(new java.awt.Color(20, 20, 40));
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton24);

        jButton25.setBackground(new java.awt.Color(200, 220, 200));
        jButton25.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton25.setForeground(new java.awt.Color(20, 20, 40));
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton25);

        jPanel3.setBackground(new java.awt.Color(60, 83, 65));

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(177, 237, 207));
        jLabel1.setText("SCORE:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(220, 162, 167));
        jLabel2.setText("Player X: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(167, 162, 227));
        jLabel3.setText("Player O: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(220, 162, 167));
        jLabel4.setText("0");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(167, 162, 227));
        jLabel5.setText("0");

        Salir.setBackground(new java.awt.Color(98, 30, 42));
        Salir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Salir.setForeground(new java.awt.Color(187, 187, 188));
        Salir.setText("SALIR");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        NuevoJuego.setBackground(new java.awt.Color(38, 50, 82));
        NuevoJuego.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NuevoJuego.setForeground(new java.awt.Color(187, 187, 188));
        NuevoJuego.setText("NUEVO JUEGO");
        NuevoJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoJuegoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NuevoJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(NuevoJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void compruebaGanador()
    {
        int rep=0;
        boolean gano=false;
        boolean empate=true;
        
        for (int i = 0; i < 5; i++) {
            if(mat[i][0] == 1 && mat[i][0] == mat[i][1] && mat[i][0] == mat[i][2] && mat[i][0] == mat[i][3])
            {
                ganador(1);
                gano=true;
                break;
            }
            if(mat[i][1] == 1 && mat[i][1] == mat[i][2] && mat[i][1] == mat[i][3] && mat[i][1] == mat[i][4])
            {
                ganador(1);
                gano=true;
                break;
            }
            
            if(mat[i][0] == 2 && mat[i][0] == mat[i][1] && mat[i][0] == mat[i][2] && mat[i][0] == mat[i][3])
            {
                ganador(2);
                gano=true;
                break;
            }
            if(mat[i][1] == 2 && mat[i][1] == mat[i][2] && mat[i][1] == mat[i][3] && mat[i][1] == mat[i][4])
            {
                ganador(2);
                gano=true;
                break;
            }
            
        }
        if(!gano)
        {
            for (int i = 0; i < 5; i++) {
                if(mat[0][i] == 1 && mat[0][i] == mat[1][i] && mat[0][i] == mat[2][i] && mat[0][i] == mat[3][i])
                {
                    ganador(1);
                    gano=true;
                    break;
                }
                if(mat[1][i] == 1 && mat[1][i] == mat[2][i] && mat[1][i] == mat[3][i] && mat[1][i] == mat[4][i])
                {
                    ganador(1);
                    gano=true;
                    break;
                }

                if(mat[0][i] == 2 && mat[0][i] == mat[1][i] && mat[0][i] == mat[2][i] && mat[0][i] == mat[3][i])
                {
                    ganador(2);
                    gano=true;
                    break;
                }
                if(mat[1][i] == 2 && mat[1][i] == mat[2][i] && mat[1][i] == mat[3][i] && mat[1][i] == mat[4][i])
                {
                    ganador(2);
                    gano=true;
                    break;
                }
            }
        }
        
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                if(mat[i][j]==0)
                {
                    empate=false;
                }
            }
        }
        
        if(empate)
        {
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
            jButton10.setEnabled(false);
            jButton11.setEnabled(false);
            jButton12.setEnabled(false);
            jButton13.setEnabled(false);
            jButton14.setEnabled(false);
            jButton15.setEnabled(false);
            jButton16.setEnabled(false);
            jButton17.setEnabled(false);
            jButton18.setEnabled(false);
            jButton19.setEnabled(false);
            jButton20.setEnabled(false);
            jButton21.setEnabled(false);
            jButton22.setEnabled(false);
            jButton23.setEnabled(false);
            jButton24.setEnabled(false);        
            jButton25.setEnabled(false);
            
            new Tie().setVisible(true);
        }
    }
    
    private void ganador(int winner)
    {
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton9.setEnabled(false);
        jButton10.setEnabled(false);
        jButton11.setEnabled(false);
        jButton12.setEnabled(false);
        jButton13.setEnabled(false);
        jButton14.setEnabled(false);
        jButton15.setEnabled(false);
        jButton16.setEnabled(false);
        jButton17.setEnabled(false);
        jButton18.setEnabled(false);
        jButton19.setEnabled(false);
        jButton20.setEnabled(false);
        jButton21.setEnabled(false);
        jButton22.setEnabled(false);
        jButton23.setEnabled(false);
        jButton24.setEnabled(false);        
        jButton25.setEnabled(false);
        
        if(winner==1)
        {
            puntosX++;
            new PXWin().setVisible(true);
        }else{
            puntosO++;
            new POWin().setVisible(true);
        }
        
        jLabel4.setText(Integer.toString(puntosX));
        jLabel5.setText(Integer.toString(puntosO));
    }
    
    private void NuevoJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoJuegoActionPerformed
        // TODO add your handling code here:
        jButton1.setText("");
        jButton1.setEnabled(true);
        jButton2.setText("");
        jButton2.setEnabled(true);
        jButton3.setText("");
        jButton3.setEnabled(true);
        jButton4.setText("");
        jButton4.setEnabled(true);
        jButton5.setText("");
        jButton5.setEnabled(true);
        jButton6.setText("");
        jButton6.setEnabled(true);
        jButton7.setText("");
        jButton7.setEnabled(true);
        jButton8.setText("");
        jButton8.setEnabled(true);
        jButton9.setText("");
        jButton9.setEnabled(true);
        jButton10.setText("");
        jButton10.setEnabled(true);
        jButton11.setText("");
        jButton11.setEnabled(true);
        jButton12.setText("");
        jButton12.setEnabled(true);
        jButton13.setText("");
        jButton13.setEnabled(true);
        jButton14.setText("");
        jButton14.setEnabled(true);
        jButton15.setText("");
        jButton15.setEnabled(true);
        jButton16.setText("");
        jButton16.setEnabled(true);
        jButton17.setText("");
        jButton17.setEnabled(true);
        jButton18.setText("");
        jButton18.setEnabled(true);
        jButton19.setText("");
        jButton19.setEnabled(true);
        jButton20.setText("");
        jButton20.setEnabled(true);
        jButton21.setText("");
        jButton21.setEnabled(true);
        jButton22.setText("");
        jButton22.setEnabled(true);
        jButton23.setText("");
        jButton23.setEnabled(true);
        jButton24.setText("");
        jButton24.setEnabled(true);
        jButton25.setText("");
        jButton25.setEnabled(true);
        
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                mat[i][j]=0;
            }
        }
        
        /*
        jButton1.setBackground(Color.LIGHT_GRAY);
        jButton2.setBackground(Color.LIGHT_GRAY);
        jButton3.setBackground(Color.LIGHT_GRAY);
        jButton4.setBackground(Color.LIGHT_GRAY);
        jButton5.setBackground(Color.LIGHT_GRAY);
        jButton6.setBackground(Color.LIGHT_GRAY);
        jButton7.setBackground(Color.LIGHT_GRAY);
        jButton8.setBackground(Color.LIGHT_GRAY);
        jButton9.setBackground(Color.LIGHT_GRAY);
        jButton10.setBackground(Color.LIGHT_GRAY);
        jButton11.setBackground(Color.LIGHT_GRAY);
        jButton12.setBackground(Color.LIGHT_GRAY);
        jButton13.setBackground(Color.LIGHT_GRAY);
        jButton14.setBackground(Color.LIGHT_GRAY);
        jButton15.setBackground(Color.LIGHT_GRAY);
        jButton16.setBackground(Color.LIGHT_GRAY);
        jButton17.setBackground(Color.LIGHT_GRAY);
        jButton18.setBackground(Color.LIGHT_GRAY);
        jButton19.setBackground(Color.LIGHT_GRAY);
        jButton20.setBackground(Color.LIGHT_GRAY);
        jButton21.setBackground(Color.LIGHT_GRAY);
        jButton22.setBackground(Color.LIGHT_GRAY);
        jButton23.setBackground(Color.LIGHT_GRAY);
        jButton24.setBackground(Color.LIGHT_GRAY);
        jButton25.setBackground(Color.LIGHT_GRAY);
        */
        
    }//GEN-LAST:event_NuevoJuegoActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(turno)
        {
            if(jButton21.getText()=="")
            {
                jButton21.setText("X");
                mat[0][4]=1;
            }else if(jButton16.getText()=="")
            {
                jButton16.setText("X");
                mat[0][3]=1;
            }else if(jButton11.getText()=="")
            {
                jButton11.setText("X");
                mat[0][2]=1;
            }else if(jButton6.getText()=="")
            {
                jButton6.setText("X");
                mat[0][1]=1;
            }else if(jButton1.getText()=="")
            {
                jButton1.setText("X");
                mat[0][0]=1;
            }else
            {
                return;
            }
            turno=false;
            compruebaGanador();
        }else{
            if(jButton21.getText()=="")
            {
                jButton21.setText("O");
                mat[0][4]=2;
            }else if(jButton16.getText()=="")
            {
                jButton16.setText("O");
                mat[0][3]=2;
            }else if(jButton11.getText()=="")
            {
                jButton11.setText("O");
                mat[0][2]=2;
            }else if(jButton6.getText()=="")
            {
                jButton6.setText("O");
                mat[0][1]=2;
            }else if(jButton1.getText()=="")
            {
                jButton1.setText("O");
                mat[0][0]=2;
            }else
            {
                return;
            }
            turno=true;
            compruebaGanador();
        }
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(turno)
        {
            if(jButton22.getText()=="")
            {
                jButton22.setText("X");
                mat[1][4]=1;
            }else if(jButton17.getText()=="")
            {
                jButton17.setText("X");
                mat[1][3]=1;
            }else if(jButton12.getText()=="")
            {
                jButton12.setText("X");
                mat[1][2]=1;
            }else if(jButton7.getText()=="")
            {
                jButton7.setText("X");
                mat[1][1]=1;
            }else if(jButton2.getText()=="")
            {
                jButton2.setText("X");
                mat[1][0]=1;
            }else
            {
                return;
            }
            turno=false;
            compruebaGanador();
        }else{
            if(jButton22.getText()=="")
            {
                jButton22.setText("O");
                mat[1][4]=2;
            }else if(jButton17.getText()=="")
            {
                jButton17.setText("O");
                mat[1][3]=2;
            }else if(jButton12.getText()=="")
            {
                jButton12.setText("O");
                mat[1][2]=2;
            }else if(jButton7.getText()=="")
            {
                jButton7.setText("O");
                mat[1][1]=2;
            }else if(jButton2.getText()=="")
            {
                jButton2.setText("O");
                mat[1][0]=2;
            }else
            {
                return;
            }
            turno=true;
            compruebaGanador();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(turno)
        {
            if(jButton23.getText()=="")
            {
                jButton23.setText("X");
                mat[2][4]=1;
            }else if(jButton18.getText()=="")
            {
                jButton18.setText("X");
                mat[2][3]=1;
            }else if(jButton13.getText()=="")
            {
                jButton13.setText("X");
                mat[2][2]=1;
            }else if(jButton8.getText()=="")
            {
                jButton8.setText("X");
                mat[2][1]=1;
            }else if(jButton3.getText()=="")
            {
                jButton3.setText("X");
                mat[2][0]=1;
            }else
            {
                return;
            }
            turno=false;
            compruebaGanador();
        }else{
            if(jButton23.getText()=="")
            {
                jButton23.setText("O");
                mat[2][4]=2;
            }else if(jButton18.getText()=="")
            {
                jButton18.setText("O");
                mat[2][3]=2;
            }else if(jButton13.getText()=="")
            {
                jButton13.setText("O");
                mat[2][2]=2;
            }else if(jButton8.getText()=="")
            {
                jButton8.setText("O");
                mat[2][1]=2;
            }else if(jButton3.getText()=="")
            {
                jButton3.setText("O");
                mat[2][0]=2;
            }else
            {
                return;
            }
            turno=true;
            compruebaGanador();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(turno)
        {
            if(jButton24.getText()=="")
            {
                jButton24.setText("X");
                mat[3][4]=1;
            }else if(jButton19.getText()=="")
            {
                jButton19.setText("X");
                mat[3][3]=1;
            }else if(jButton14.getText()=="")
            {
                jButton14.setText("X");
                mat[3][2]=1;
            }else if(jButton9.getText()=="")
            {
                jButton9.setText("X");
                mat[3][1]=1;
            }else if(jButton4.getText()=="")
            {
                jButton4.setText("X");
                mat[3][0]=1;
            }else
            {
                return;
            }
            turno=false;
            compruebaGanador();
        }else{
            if(jButton24.getText()=="")
            {
                jButton24.setText("O");
                mat[3][4]=2;
            }else if(jButton19.getText()=="")
            {
                jButton19.setText("O");
                mat[3][3]=2;
            }else if(jButton14.getText()=="")
            {
                jButton14.setText("O");
                mat[3][2]=2;
            }else if(jButton9.getText()=="")
            {
                jButton9.setText("O");
                mat[3][1]=2;
            }else if(jButton4.getText()=="")
            {
                jButton4.setText("O");
                mat[3][0]=2;
            }else
            {
                return;
            }
            turno=true;
            compruebaGanador();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(turno)
        {
            if(jButton25.getText()=="")
            {
                jButton25.setText("X");
                mat[4][4]=1;
            }else if(jButton20.getText()=="")
            {
                jButton20.setText("X");
                mat[4][3]=1;
            }else if(jButton15.getText()=="")
            {
                jButton15.setText("X");
                mat[4][2]=1;
            }else if(jButton10.getText()=="")
            {
                jButton10.setText("X");
                mat[4][1]=1;
            }else if(jButton5.getText()=="")
            {
                jButton5.setText("X");
                mat[4][0]=1;
            }else
            {
                return;
            }
            turno=false;
            compruebaGanador();
        }else{
            if(jButton25.getText()=="")
            {
                jButton25.setText("O");
                mat[4][4]=2;
            }else if(jButton20.getText()=="")
            {
                jButton20.setText("O");
                mat[4][3]=2;
            }else if(jButton15.getText()=="")
            {
                jButton15.setText("O");
                mat[4][2]=2;
            }else if(jButton10.getText()=="")
            {
                jButton10.setText("O");
                mat[4][1]=2;
            }else if(jButton5.getText()=="")
            {
                jButton5.setText("O");
                mat[4][0]=2;
            }else
            {
                return;
            }
            turno=true;
            compruebaGanador();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(turno)
        {
            if(jButton21.getText()=="")
            {
                jButton21.setText("X");
                mat[0][4]=1;
            }else if(jButton16.getText()=="")
            {
                jButton16.setText("X");
                mat[0][3]=1;
            }else if(jButton11.getText()=="")
            {
                jButton11.setText("X");
                mat[0][2]=1;
            }else if(jButton6.getText()=="")
            {
                jButton6.setText("X");
                mat[0][1]=1;
            }else if(jButton1.getText()=="")
            {
                jButton1.setText("X");
                mat[0][0]=1;
            }else
            {
                return;
            }
            turno=false;
            compruebaGanador();
        }else{
            if(jButton21.getText()=="")
            {
                jButton21.setText("O");
                mat[0][4]=2;
            }else if(jButton16.getText()=="")
            {
                jButton16.setText("O");
                mat[0][3]=2;
            }else if(jButton11.getText()=="")
            {
                jButton11.setText("O");
                mat[0][2]=2;
            }else if(jButton6.getText()=="")
            {
                jButton6.setText("O");
                mat[0][1]=2;
            }else if(jButton1.getText()=="")
            {
                jButton1.setText("O");
                mat[0][0]=2;
            }else
            {
                return;
            }
            turno=true;
            compruebaGanador();
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(turno)
        {
            if(jButton22.getText()=="")
            {
                jButton22.setText("X");
                mat[1][4]=1;
            }else if(jButton17.getText()=="")
            {
                jButton17.setText("X");
                mat[1][3]=1;
            }else if(jButton12.getText()=="")
            {
                jButton12.setText("X");
                mat[1][2]=1;
            }else if(jButton7.getText()=="")
            {
                jButton7.setText("X");
                mat[1][1]=1;
            }else if(jButton2.getText()=="")
            {
                jButton2.setText("X");
                mat[1][0]=1;
            }else
            {
                return;
            }
            turno=false;
            compruebaGanador();
        }else{
            if(jButton22.getText()=="")
            {
                jButton22.setText("O");
                mat[1][4]=2;
            }else if(jButton17.getText()=="")
            {
                jButton17.setText("O");
                mat[1][3]=2;
            }else if(jButton12.getText()=="")
            {
                jButton12.setText("O");
                mat[1][2]=2;
            }else if(jButton7.getText()=="")
            {
                jButton7.setText("O");
                mat[1][1]=2;
            }else if(jButton2.getText()=="")
            {
                jButton2.setText("O");
                mat[1][0]=2;
            }else
            {
                return;
            }
            turno=true;
            compruebaGanador();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(turno)
        {
            if(jButton23.getText()=="")
            {
                jButton23.setText("X");
                mat[2][4]=1;
            }else if(jButton18.getText()=="")
            {
                jButton18.setText("X");
                mat[2][3]=1;
            }else if(jButton13.getText()=="")
            {
                jButton13.setText("X");
                mat[2][2]=1;
            }else if(jButton8.getText()=="")
            {
                jButton8.setText("X");
                mat[2][1]=1;
            }else if(jButton3.getText()=="")
            {
                jButton3.setText("X");
                mat[2][0]=1;
            }else
            {
                return;
            }
            turno=false;
            compruebaGanador();
        }else{
            if(jButton23.getText()=="")
            {
                jButton23.setText("O");
                mat[2][4]=2;
            }else if(jButton18.getText()=="")
            {
                jButton18.setText("O");
                mat[2][3]=2;
            }else if(jButton13.getText()=="")
            {
                jButton13.setText("O");
                mat[2][2]=2;
            }else if(jButton8.getText()=="")
            {
                jButton8.setText("O");
                mat[2][1]=2;
            }else if(jButton3.getText()=="")
            {
                jButton3.setText("O");
                mat[2][0]=2;
            }else
            {
                return;
            }
            turno=true;
            compruebaGanador();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if(turno)
        {
            if(jButton24.getText()=="")
            {
                jButton24.setText("X");
                mat[3][4]=1;
            }else if(jButton19.getText()=="")
            {
                jButton19.setText("X");
                mat[3][3]=1;
            }else if(jButton14.getText()=="")
            {
                jButton14.setText("X");
                mat[3][2]=1;
            }else if(jButton9.getText()=="")
            {
                jButton9.setText("X");
                mat[3][1]=1;
            }else if(jButton4.getText()=="")
            {
                jButton4.setText("X");
                mat[3][0]=1;
            }else
            {
                return;
            }
            turno=false;
            compruebaGanador();
        }else{
            if(jButton24.getText()=="")
            {
                jButton24.setText("O");
                mat[3][4]=2;
            }else if(jButton19.getText()=="")
            {
                jButton19.setText("O");
                mat[3][3]=2;
            }else if(jButton14.getText()=="")
            {
                jButton14.setText("O");
                mat[3][2]=2;
            }else if(jButton9.getText()=="")
            {
                jButton9.setText("O");
                mat[3][1]=2;
            }else if(jButton4.getText()=="")
            {
                jButton4.setText("O");
                mat[3][0]=2;
            }else
            {
                return;
            }
            turno=true;
            compruebaGanador();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        if(turno)
        {
            if(jButton25.getText()=="")
            {
                jButton25.setText("X");
                mat[4][4]=1;
            }else if(jButton20.getText()=="")
            {
                jButton20.setText("X");
                mat[4][3]=1;
            }else if(jButton15.getText()=="")
            {
                jButton15.setText("X");
                mat[4][2]=1;
            }else if(jButton10.getText()=="")
            {
                jButton10.setText("X");
                mat[4][1]=1;
            }else if(jButton5.getText()=="")
            {
                jButton5.setText("X");
                mat[4][0]=1;
            }else
            {
                return;
            }
            turno=false;
            compruebaGanador();
        }else{
            if(jButton25.getText()=="")
            {
                jButton25.setText("O");
                mat[4][4]=2;
            }else if(jButton20.getText()=="")
            {
                jButton20.setText("O");
                mat[4][3]=2;
            }else if(jButton15.getText()=="")
            {
                jButton15.setText("O");
                mat[4][2]=2;
            }else if(jButton10.getText()=="")
            {
                jButton10.setText("O");
                mat[4][1]=2;
            }else if(jButton5.getText()=="")
            {
                jButton5.setText("O");
                mat[4][0]=2;
            }else
            {
                return;
            }
            turno=true;
            compruebaGanador();
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        if(turno)
        {
            if(jButton21.getText()=="")
            {
                jButton21.setText("X");
                mat[0][4]=1;
            }else if(jButton16.getText()=="")
            {
                jButton16.setText("X");
                mat[0][3]=1;
            }else if(jButton11.getText()=="")
            {
                jButton11.setText("X");
                mat[0][2]=1;
            }else if(jButton6.getText()=="")
            {
                jButton6.setText("X");
                mat[0][1]=1;
            }else if(jButton1.getText()=="")
            {
                jButton1.setText("X");
                mat[0][0]=1;
            }else
            {
                return;
            }
            turno=false;
            compruebaGanador();
        }else{
            if(jButton21.getText()=="")
            {
                jButton21.setText("O");
                mat[0][4]=2;
            }else if(jButton16.getText()=="")
            {
                jButton16.setText("O");
                mat[0][3]=2;
            }else if(jButton11.getText()=="")
            {
                jButton11.setText("O");
                mat[0][2]=2;
            }else if(jButton6.getText()=="")
            {
                jButton6.setText("O");
                mat[0][1]=2;
            }else if(jButton1.getText()=="")
            {
                jButton1.setText("O");
                mat[0][0]=2;
            }else
            {
                return;
            }
            turno=true;
            compruebaGanador();
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        if(turno)
        {
            if(jButton22.getText()=="")
            {
                jButton22.setText("X");
                mat[1][4]=1;
            }else if(jButton17.getText()=="")
            {
                jButton17.setText("X");
                mat[1][3]=1;
            }else if(jButton12.getText()=="")
            {
                jButton12.setText("X");
                mat[1][2]=1;
            }else if(jButton7.getText()=="")
            {
                jButton7.setText("X");
                mat[1][1]=1;
            }else if(jButton2.getText()=="")
            {
                jButton2.setText("X");
                mat[1][0]=1;
            }else
            {
                return;
            }
            turno=false;
            compruebaGanador();
        }else{
            if(jButton22.getText()=="")
            {
                jButton22.setText("O");
                mat[1][4]=2;
            }else if(jButton17.getText()=="")
            {
                jButton17.setText("O");
                mat[1][3]=2;
            }else if(jButton12.getText()=="")
            {
                jButton12.setText("O");
                mat[1][2]=2;
            }else if(jButton7.getText()=="")
            {
                jButton7.setText("O");
                mat[1][1]=2;
            }else if(jButton2.getText()=="")
            {
                jButton2.setText("O");
                mat[1][0]=2;
            }else
            {
                return;
            }
            turno=true;
            compruebaGanador();
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        if(turno)
        {
            if(jButton23.getText()=="")
            {
                jButton23.setText("X");
                mat[2][4]=1;
            }else if(jButton18.getText()=="")
            {
                jButton18.setText("X");
                mat[2][3]=1;
            }else if(jButton13.getText()=="")
            {
                jButton13.setText("X");
                mat[2][2]=1;
            }else if(jButton8.getText()=="")
            {
                jButton8.setText("X");
                mat[2][1]=1;
            }else if(jButton3.getText()=="")
            {
                jButton3.setText("X");
                mat[2][0]=1;
            }else
            {
                return;
            }
            turno=false;
            compruebaGanador();
        }else{
            if(jButton23.getText()=="")
            {
                jButton23.setText("O");
                mat[2][4]=2;
            }else if(jButton18.getText()=="")
            {
                jButton18.setText("O");
                mat[2][3]=2;
            }else if(jButton13.getText()=="")
            {
                jButton13.setText("O");
                mat[2][2]=2;
            }else if(jButton8.getText()=="")
            {
                jButton8.setText("O");
                mat[2][1]=2;
            }else if(jButton3.getText()=="")
            {
                jButton3.setText("O");
                mat[2][0]=2;
            }else
            {
                return;
            }
            turno=true;
            compruebaGanador();
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        if(turno)
        {
            if(jButton24.getText()=="")
            {
                jButton24.setText("X");
                mat[3][4]=1;
            }else if(jButton19.getText()=="")
            {
                jButton19.setText("X");
                mat[3][3]=1;
            }else if(jButton14.getText()=="")
            {
                jButton14.setText("X");
                mat[3][2]=1;
            }else if(jButton9.getText()=="")
            {
                jButton9.setText("X");
                mat[3][1]=1;
            }else if(jButton4.getText()=="")
            {
                jButton4.setText("X");
                mat[3][0]=1;
            }else
            {
                return;
            }
            turno=false;
            compruebaGanador();
        }else{
            if(jButton24.getText()=="")
            {
                jButton24.setText("O");
                mat[3][4]=2;
            }else if(jButton19.getText()=="")
            {
                jButton19.setText("O");
                mat[3][3]=2;
            }else if(jButton14.getText()=="")
            {
                jButton14.setText("O");
                mat[3][2]=2;
            }else if(jButton9.getText()=="")
            {
                jButton9.setText("O");
                mat[3][1]=2;
            }else if(jButton4.getText()=="")
            {
                jButton4.setText("O");
                mat[3][0]=2;
            }else
            {
                return;
            }
            turno=true;
            compruebaGanador();
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        if(turno)
        {
            if(jButton25.getText()=="")
            {
                jButton25.setText("X");
                mat[4][4]=1;
            }else if(jButton20.getText()=="")
            {
                jButton20.setText("X");
                mat[4][3]=1;
            }else if(jButton15.getText()=="")
            {
                jButton15.setText("X");
                mat[4][2]=1;
            }else if(jButton10.getText()=="")
            {
                jButton10.setText("X");
                mat[4][1]=1;
            }else if(jButton5.getText()=="")
            {
                jButton5.setText("X");
                mat[4][0]=1;
            }else
            {
                return;
            }
            turno=false;
            compruebaGanador();
        }else{
            if(jButton25.getText()=="")
            {
                jButton25.setText("O");
                mat[4][4]=2;
            }else if(jButton20.getText()=="")
            {
                jButton20.setText("O");
                mat[4][3]=2;
            }else if(jButton15.getText()=="")
            {
                jButton15.setText("O");
                mat[4][2]=2;
            }else if(jButton10.getText()=="")
            {
                jButton10.setText("O");
                mat[4][1]=2;
            }else if(jButton5.getText()=="")
            {
                jButton5.setText("O");
                mat[4][0]=2;
            }else
            {
                return;
            }
            turno=true;
            compruebaGanador();
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        if(turno)
        {
            if(jButton21.getText()=="")
            {
                jButton21.setText("X");
                mat[0][4]=1;
            }else if(jButton16.getText()=="")
            {
                jButton16.setText("X");
                mat[0][3]=1;
            }else if(jButton11.getText()=="")
            {
                jButton11.setText("X");
                mat[0][2]=1;
            }else if(jButton6.getText()=="")
            {
                jButton6.setText("X");
                mat[0][1]=1;
            }else if(jButton1.getText()=="")
            {
                jButton1.setText("X");
                mat[0][0]=1;
            }else
            {
                return;
            }
            turno=false;
            compruebaGanador();
        }else{
            if(jButton21.getText()=="")
            {
                jButton21.setText("O");
                mat[0][4]=2;
            }else if(jButton16.getText()=="")
            {
                jButton16.setText("O");
                mat[0][3]=2;
            }else if(jButton11.getText()=="")
            {
                jButton11.setText("O");
                mat[0][2]=2;
            }else if(jButton6.getText()=="")
            {
                jButton6.setText("O");
                mat[0][1]=2;
            }else if(jButton1.getText()=="")
            {
                jButton1.setText("O");
                mat[0][0]=2;
            }else
            {
                return;
            }
            turno=true;
            compruebaGanador();
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        if(turno)
        {
            if(jButton22.getText()=="")
            {
                jButton22.setText("X");
                mat[1][4]=1;
            }else if(jButton17.getText()=="")
            {
                jButton17.setText("X");
                mat[1][3]=1;
            }else if(jButton12.getText()=="")
            {
                jButton12.setText("X");
                mat[1][2]=1;
            }else if(jButton7.getText()=="")
            {
                jButton7.setText("X");
                mat[1][1]=1;
            }else if(jButton2.getText()=="")
            {
                jButton2.setText("X");
                mat[1][0]=1;
            }else
            {
                return;
            }
            turno=false;
            compruebaGanador();
        }else{
            if(jButton22.getText()=="")
            {
                jButton22.setText("O");
                mat[1][4]=2;
            }else if(jButton17.getText()=="")
            {
                jButton17.setText("O");
                mat[1][3]=2;
            }else if(jButton12.getText()=="")
            {
                jButton12.setText("O");
                mat[1][2]=2;
            }else if(jButton7.getText()=="")
            {
                jButton7.setText("O");
                mat[1][1]=2;
            }else if(jButton2.getText()=="")
            {
                jButton2.setText("O");
                mat[1][0]=2;
            }else
            {
                return;
            }
            turno=true;
            compruebaGanador();
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        if(turno)
        {
            if(jButton23.getText()=="")
            {
                jButton23.setText("X");
                mat[2][4]=1;
            }else if(jButton18.getText()=="")
            {
                jButton18.setText("X");
                mat[2][3]=1;
            }else if(jButton13.getText()=="")
            {
                jButton13.setText("X");
                mat[2][2]=1;
            }else if(jButton8.getText()=="")
            {
                jButton8.setText("X");
                mat[2][1]=1;
            }else if(jButton3.getText()=="")
            {
                jButton3.setText("X");
                mat[2][0]=1;
            }else
            {
                return;
            }
            turno=false;
            compruebaGanador();
        }else{
            if(jButton23.getText()=="")
            {
                jButton23.setText("O");
                mat[2][4]=2;
            }else if(jButton18.getText()=="")
            {
                jButton18.setText("O");
                mat[2][3]=2;
            }else if(jButton13.getText()=="")
            {
                jButton13.setText("O");
                mat[2][2]=2;
            }else if(jButton8.getText()=="")
            {
                jButton8.setText("O");
                mat[2][1]=2;
            }else if(jButton3.getText()=="")
            {
                jButton3.setText("O");
                mat[2][0]=2;
            }else
            {
                return;
            }
            turno=true;
            compruebaGanador();
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        if(turno)
        {
            if(jButton24.getText()=="")
            {
                jButton24.setText("X");
                mat[3][4]=1;
            }else if(jButton19.getText()=="")
            {
                jButton19.setText("X");
                mat[3][3]=1;
            }else if(jButton14.getText()=="")
            {
                jButton14.setText("X");
                mat[3][2]=1;
            }else if(jButton9.getText()=="")
            {
                jButton9.setText("X");
                mat[3][1]=1;
            }else if(jButton4.getText()=="")
            {
                jButton4.setText("X");
                mat[3][0]=1;
            }else
            {
                return;
            }
            turno=false;
            compruebaGanador();
        }else{
            if(jButton24.getText()=="")
            {
                jButton24.setText("O");
                mat[3][4]=2;
            }else if(jButton19.getText()=="")
            {
                jButton19.setText("O");
                mat[3][3]=2;
            }else if(jButton14.getText()=="")
            {
                jButton14.setText("O");
                mat[3][2]=2;
            }else if(jButton9.getText()=="")
            {
                jButton9.setText("O");
                mat[3][1]=2;
            }else if(jButton4.getText()=="")
            {
                jButton4.setText("O");
                mat[3][0]=2;
            }else
            {
                return;
            }
            turno=true;
            compruebaGanador();
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        if(turno)
        {
            if(jButton25.getText()=="")
            {
                jButton25.setText("X");
                mat[4][4]=1;
            }else if(jButton20.getText()=="")
            {
                jButton20.setText("X");
                mat[4][3]=1;
            }else if(jButton15.getText()=="")
            {
                jButton15.setText("X");
                mat[4][2]=1;
            }else if(jButton10.getText()=="")
            {
                jButton10.setText("X");
                mat[4][1]=1;
            }else if(jButton5.getText()=="")
            {
                jButton5.setText("X");
                mat[4][0]=1;
            }else
            {
                return;
            }
            turno=false;
            compruebaGanador();
        }else{
            if(jButton25.getText()=="")
            {
                jButton25.setText("O");
                mat[4][4]=2;
            }else if(jButton20.getText()=="")
            {
                jButton20.setText("O");
                mat[4][3]=2;
            }else if(jButton15.getText()=="")
            {
                jButton15.setText("O");
                mat[4][2]=2;
            }else if(jButton10.getText()=="")
            {
                jButton10.setText("O");
                mat[4][1]=2;
            }else if(jButton5.getText()=="")
            {
                jButton5.setText("O");
                mat[4][0]=2;
            }else
            {
                return;
            }
            turno=true;
            compruebaGanador();
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        if(turno)
        {
            if(jButton21.getText()=="")
            {
                jButton21.setText("X");
                mat[0][4]=1;
            }else if(jButton16.getText()=="")
            {
                jButton16.setText("X");
                mat[0][3]=1;
            }else if(jButton11.getText()=="")
            {
                jButton11.setText("X");
                mat[0][2]=1;
            }else if(jButton6.getText()=="")
            {
                jButton6.setText("X");
                mat[0][1]=1;
            }else if(jButton1.getText()=="")
            {
                jButton1.setText("X");
                mat[0][0]=1;
            }else
            {
                return;
            }
            turno=false;
            compruebaGanador();
        }else{
            if(jButton21.getText()=="")
            {
                jButton21.setText("O");
                mat[0][4]=2;
            }else if(jButton16.getText()=="")
            {
                jButton16.setText("O");
                mat[0][3]=2;
            }else if(jButton11.getText()=="")
            {
                jButton11.setText("O");
                mat[0][2]=2;
            }else if(jButton6.getText()=="")
            {
                jButton6.setText("O");
                mat[0][1]=2;
            }else if(jButton1.getText()=="")
            {
                jButton1.setText("O");
                mat[0][0]=2;
            }else
            {
                return;
            }
            turno=true;
            compruebaGanador();
        }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        if(turno)
        {
            if(jButton22.getText()=="")
            {
                jButton22.setText("X");
                mat[1][4]=1;
            }else if(jButton17.getText()=="")
            {
                jButton17.setText("X");
                mat[1][3]=1;
            }else if(jButton12.getText()=="")
            {
                jButton12.setText("X");
                mat[1][2]=1;
            }else if(jButton7.getText()=="")
            {
                jButton7.setText("X");
                mat[1][1]=1;
            }else if(jButton2.getText()=="")
            {
                jButton2.setText("X");
                mat[1][0]=1;
            }else
            {
                return;
            }
            turno=false;
            compruebaGanador();
        }else{
            if(jButton22.getText()=="")
            {
                jButton22.setText("O");
                mat[1][4]=2;
            }else if(jButton17.getText()=="")
            {
                jButton17.setText("O");
                mat[1][3]=2;
            }else if(jButton12.getText()=="")
            {
                jButton12.setText("O");
                mat[1][2]=2;
            }else if(jButton7.getText()=="")
            {
                jButton7.setText("O");
                mat[1][1]=2;
            }else if(jButton2.getText()=="")
            {
                jButton2.setText("O");
                mat[1][0]=2;
            }else
            {
                return;
            }
            turno=true;
            compruebaGanador();
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        if(turno)
        {
            if(jButton23.getText()=="")
            {
                jButton23.setText("X");
                mat[2][4]=1;
            }else if(jButton18.getText()=="")
            {
                jButton18.setText("X");
                mat[2][3]=1;
            }else if(jButton13.getText()=="")
            {
                jButton13.setText("X");
                mat[2][2]=1;
            }else if(jButton8.getText()=="")
            {
                jButton8.setText("X");
                mat[2][1]=1;
            }else if(jButton3.getText()=="")
            {
                jButton3.setText("X");
                mat[2][0]=1;
            }else
            {
                return;
            }
            turno=false;
            compruebaGanador();
        }else{
            if(jButton23.getText()=="")
            {
                jButton23.setText("O");
                mat[2][4]=2;
            }else if(jButton18.getText()=="")
            {
                jButton18.setText("O");
                mat[2][3]=2;
            }else if(jButton13.getText()=="")
            {
                jButton13.setText("O");
                mat[2][2]=2;
            }else if(jButton8.getText()=="")
            {
                jButton8.setText("O");
                mat[2][1]=2;
            }else if(jButton3.getText()=="")
            {
                jButton3.setText("O");
                mat[2][0]=2;
            }else
            {
                return;
            }
            turno=true;
            compruebaGanador();
        }
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        if(turno)
        {
            if(jButton24.getText()=="")
            {
                jButton24.setText("X");
                mat[3][4]=1;
            }else if(jButton19.getText()=="")
            {
                jButton19.setText("X");
                mat[3][3]=1;
            }else if(jButton14.getText()=="")
            {
                jButton14.setText("X");
                mat[3][2]=1;
            }else if(jButton9.getText()=="")
            {
                jButton9.setText("X");
                mat[3][1]=1;
            }else if(jButton4.getText()=="")
            {
                jButton4.setText("X");
                mat[3][0]=1;
            }else
            {
                return;
            }
            turno=false;
            compruebaGanador();
        }else{
            if(jButton24.getText()=="")
            {
                jButton24.setText("O");
                mat[3][4]=2;
            }else if(jButton19.getText()=="")
            {
                jButton19.setText("O");
                mat[3][3]=2;
            }else if(jButton14.getText()=="")
            {
                jButton14.setText("O");
                mat[3][2]=2;
            }else if(jButton9.getText()=="")
            {
                jButton9.setText("O");
                mat[3][1]=2;
            }else if(jButton4.getText()=="")
            {
                jButton4.setText("O");
                mat[3][0]=2;
            }else
            {
                return;
            }
            turno=true;
            compruebaGanador();
        }
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
        if(turno)
        {
            if(jButton25.getText()=="")
            {
                jButton25.setText("X");
                mat[4][4]=1;
            }else if(jButton20.getText()=="")
            {
                jButton20.setText("X");
                mat[4][3]=1;
            }else if(jButton15.getText()=="")
            {
                jButton15.setText("X");
                mat[4][2]=1;
            }else if(jButton10.getText()=="")
            {
                jButton10.setText("X");
                mat[4][1]=1;
            }else if(jButton5.getText()=="")
            {
                jButton5.setText("X");
                mat[4][0]=1;
            }else
            {
                return;
            }
            turno=false;
            compruebaGanador();
        }else{
            if(jButton25.getText()=="")
            {
                jButton25.setText("O");
                mat[4][4]=2;
            }else if(jButton20.getText()=="")
            {
                jButton20.setText("O");
                mat[4][3]=2;
            }else if(jButton15.getText()=="")
            {
                jButton15.setText("O");
                mat[4][2]=2;
            }else if(jButton10.getText()=="")
            {
                jButton10.setText("O");
                mat[4][1]=2;
            }else if(jButton5.getText()=="")
            {
                jButton5.setText("O");
                mat[4][0]=2;
            }else
            {
                return;
            }
            turno=true;
            compruebaGanador();
        }
    }//GEN-LAST:event_jButton25ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NuevoJuego;
    private javax.swing.JButton Salir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
